<?php

declare(strict_types=1);

use Karoor\Core\Database;
use Karoor\Core\Helpers;
use Karoor\Core\Response;
use Karoor\Core\Validator;

if(!defined('KAROOR_BOOTSTRAPPED')){http_response_code(404);exit;}
$financeUser=$auth->requireAuth();$financeCompany=(int)$financeUser['company_id'];$financeMethod=Helpers::requestMethod();$financeResource=$apiAction==='index'?'trial-balance':$apiAction;$financeId=isset($apiSegments[1])&&ctype_digit((string)$apiSegments[1])?(int)$apiSegments[1]:null;$financeAction=$financeId===null?null:($apiSegments[2]??null);
function karoor_finance_input():array{try{return Helpers::requestData();}catch(RuntimeException){Response::error('The request body is invalid.',[],400);}}
function karoor_finance_validate(array$input,array$rules):array{$v=new Validator($input,$rules);if(!$v->passes())Response::validation($v->errors());return$v->validated();}
function karoor_finance_dates():array{$start=is_string($_GET['start_date']??null)?$_GET['start_date']:date('Y-01-01');$end=is_string($_GET['end_date']??null)?$_GET['end_date']:date('Y-m-d');foreach(['start_date'=>$start,'end_date'=>$end]as$key=>$value){$date=DateTimeImmutable::createFromFormat('!Y-m-d',$value);if($date===false||$date->format('Y-m-d')!==$value)Response::validation([$key=>['A valid Y-m-d date is required.']]);}if($start>$end)Response::validation(['date_range'=>['The start date must not follow the end date.']]);return[$start,$end];}
function karoor_finance_journal(Database$db,int$id,int$company,bool$lock=false):array{$row=$db->fetchOne('SELECT * FROM journal_entries WHERE id=:id AND company_id=:company'.($lock?' FOR UPDATE':''),['id'=>$id,'company'=>$company]);if($row===null)throw new DomainException('The journal entry was not found.');return$row;}
function karoor_finance_journal_detail(Database$db,int$id,int$company):array{$row=karoor_finance_journal($db,$id,$company);$row['lines']=$db->fetchAll('SELECT jl.*,coa.code account_code,coa.name account_name FROM journal_entry_lines jl INNER JOIN chart_of_accounts coa ON coa.id=jl.chart_account_id WHERE jl.journal_entry_id=:id ORDER BY jl.id',['id'=>$id]);return$row;}
function karoor_finance_post(Database$db,array$user,array$journal):void{$lines=$db->fetchAll('SELECT debit,credit FROM journal_entry_lines WHERE journal_entry_id=:id',['id'=>(int)$journal['id']]);$debit=0.0;$credit=0.0;foreach($lines as$line){$debit+=(float)$line['debit'];$credit+=(float)$line['credit'];}if($lines===[]||abs($debit-$credit)>0.0001)throw new DomainException('The journal entry must contain balanced debit and credit lines.');$db->execute('UPDATE journal_entries SET status=\'POSTED\',posted_at=NOW(),posted_by=:user WHERE id=:id',['user'=>(int)$user['id'],'id'=>(int)$journal['id']]);}

if($financeResource==='chart-of-accounts'){
    if($financeMethod==='GET'){$auth->requirePermission('finance.view');Response::success($database->fetchAll('SELECT coa.*,p.code parent_code,p.name parent_name,COALESCE(SUM(CASE WHEN je.status IN (\'POSTED\',\'REVERSED\') THEN jl.debit-jl.credit ELSE 0 END),0) balance FROM chart_of_accounts coa LEFT JOIN chart_of_accounts p ON p.id=coa.parent_id LEFT JOIN journal_entry_lines jl ON jl.chart_account_id=coa.id LEFT JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE coa.company_id=:company AND coa.deleted_at IS NULL GROUP BY coa.id ORDER BY coa.code',['company'=>$financeCompany]));}
    if(in_array($financeMethod,['POST','PUT','PATCH'],true)){$auth->requirePermission($financeMethod==='POST'?'finance.create':'finance.edit');$data=karoor_finance_validate(karoor_finance_input(),['code'=>'required|string|max_length:30','name'=>'required|string|max_length:150','parent_id'=>'sometimes|nullable|integer|min:1','account_type'=>'required|in:ASSET,LIABILITY,EQUITY,REVENUE,EXPENSE','account_subtype'=>'required|string|max_length:60','normal_balance'=>'required|in:DEBIT,CREDIT','is_control_account'=>'sometimes|boolean','allow_manual_entries'=>'sometimes|boolean','is_active'=>'sometimes|boolean']);try{$id=$database->transaction(function(Database$db)use($data,$financeId,$financeCompany,$financeUser,$auditLogger):int{$old=$financeId===null?null:$db->fetchOne('SELECT * FROM chart_of_accounts WHERE id=:id AND company_id=:company AND deleted_at IS NULL FOR UPDATE',['id'=>$financeId,'company'=>$financeCompany]);if($financeId!==null&&$old===null)throw new DomainException('The account was not found.');if($old!==null&&(bool)$old['is_system'])throw new DomainException('System accounts cannot be structurally edited.');if(isset($data['parent_id'])&&$data['parent_id']!==null&&$db->fetchOne('SELECT id FROM chart_of_accounts WHERE id=:id AND company_id=:company AND deleted_at IS NULL',['id'=>(int)$data['parent_id'],'company'=>$financeCompany])===null)throw new DomainException('The parent account is unavailable.');$values=['company_id'=>$financeCompany,'parent_id'=>$data['parent_id']??null,'code'=>$data['code'],'name'=>$data['name'],'account_type'=>$data['account_type'],'account_subtype'=>$data['account_subtype'],'normal_balance'=>$data['normal_balance'],'is_control_account'=>$data['is_control_account']??0,'allow_manual_entries'=>$data['allow_manual_entries']??1,'is_system'=>0,'is_active'=>$data['is_active']??1];if($financeId===null)$id=$db->insert('chart_of_accounts',$values);else{$db->execute('UPDATE chart_of_accounts SET parent_id=:parent,code=:code,name=:name,account_type=:type,account_subtype=:subtype,normal_balance=:normal,is_control_account=:control,allow_manual_entries=:manual,is_active=:active WHERE id=:id',['parent'=>$values['parent_id'],'code'=>$values['code'],'name'=>$values['name'],'type'=>$values['account_type'],'subtype'=>$values['account_subtype'],'normal'=>$values['normal_balance'],'control'=>$values['is_control_account'],'manual'=>$values['allow_manual_entries'],'active'=>$values['is_active'],'id'=>$financeId]);$id=$financeId;}$auditLogger->log($financeId===null?'CREATE':'UPDATE','finance',$id,$old,$values,'chart_of_accounts',(int)$financeUser['id'],$financeCompany);return$id;});}catch(DomainException$e){Response::error($e->getMessage(),[],422);}Response::success(['id'=>$id],$financeId===null?'Chart account created.':'Chart account updated.',[],$financeId===null?201:200);}
}
if($financeResource==='accounts'){
    if($financeMethod==='GET'){$auth->requirePermission('finance.view');Response::success($database->fetchAll('SELECT a.*,coa.code chart_code,coa.name chart_name,COALESCE(SUM(CASE WHEN p.direction=\'IN\' THEN p.amount ELSE -p.amount END),0)+a.opening_balance balance FROM accounts a INNER JOIN chart_of_accounts coa ON coa.id=a.chart_account_id LEFT JOIN payments p ON p.account_id=a.id AND p.deleted_at IS NULL WHERE a.company_id=:company AND a.deleted_at IS NULL GROUP BY a.id ORDER BY a.name',['company'=>$financeCompany]));}
    if(in_array($financeMethod,['POST','PUT','PATCH'],true)){$auth->requirePermission($financeMethod==='POST'?'finance.create':'finance.edit');$data=karoor_finance_validate(karoor_finance_input(),['chart_account_id'=>'required|integer|min:1','name'=>'required|string|max_length:150','account_kind'=>'required|in:CASH,BANK,MOBILE_MONEY,OTHER','account_number'=>'sometimes|nullable|string|max_length:100','bank_name'=>'sometimes|nullable|string|max_length:150','currency_code'=>'sometimes|string|min_length:3|max_length:3','opening_balance'=>'sometimes|numeric','is_default'=>'sometimes|boolean','is_active'=>'sometimes|boolean']);try{$id=$database->transaction(function(Database$db)use($data,$financeId,$financeCompany,$financeUser,$auditLogger):int{$chart=$db->fetchOne('SELECT id FROM chart_of_accounts WHERE id=:id AND company_id=:company AND account_type=\'ASSET\' AND deleted_at IS NULL',['id'=>(int)$data['chart_account_id'],'company'=>$financeCompany]);if($chart===null)throw new DomainException('The selected asset account is unavailable.');if(($data['is_default']??false))$db->execute('UPDATE accounts SET is_default=0 WHERE company_id=:company AND account_kind=:kind',['company'=>$financeCompany,'kind'=>$data['account_kind']]);$values=['company_id'=>$financeCompany,'chart_account_id'=>(int)$data['chart_account_id'],'name'=>$data['name'],'account_kind'=>$data['account_kind'],'account_number'=>$data['account_number']??null,'bank_name'=>$data['bank_name']??null,'currency_code'=>strtoupper((string)($data['currency_code']??'ETB')),'opening_balance'=>$data['opening_balance']??0,'is_default'=>$data['is_default']??0,'is_active'=>$data['is_active']??1];if($financeId===null){$id=$db->insert('accounts',$values);$old=null;}else{$old=$db->fetchOne('SELECT * FROM accounts WHERE id=:id AND company_id=:company AND deleted_at IS NULL FOR UPDATE',['id'=>$financeId,'company'=>$financeCompany]);if($old===null)throw new DomainException('The financial account was not found.');$db->execute('UPDATE accounts SET chart_account_id=:chart,name=:name,account_kind=:kind,account_number=:number,bank_name=:bank,currency_code=:currency,is_default=:default_flag,is_active=:active WHERE id=:id',['chart'=>$values['chart_account_id'],'name'=>$values['name'],'kind'=>$values['account_kind'],'number'=>$values['account_number'],'bank'=>$values['bank_name'],'currency'=>$values['currency_code'],'default_flag'=>$values['is_default'],'active'=>$values['is_active'],'id'=>$financeId]);$id=$financeId;}$auditLogger->log($financeId===null?'CREATE':'UPDATE','finance',$id,$old,$values,'accounts',(int)$financeUser['id'],$financeCompany);return$id;});}catch(DomainException$e){Response::error($e->getMessage(),[],422);}Response::success(['id'=>$id],$financeId===null?'Account created.':'Account updated.',[],$financeId===null?201:200);}
}
if($financeResource==='journals'){
    if($financeMethod==='GET'){ $auth->requirePermission('finance.view');if($financeId!==null){try{Response::success(karoor_finance_journal_detail($database,$financeId,$financeCompany));}catch(DomainException$e){Response::notFound($e->getMessage());}}[$start,$end]=karoor_finance_dates();$pagination=Helpers::pagination();$rows=$database->fetchAll('SELECT je.*,u.full_name created_by_name,COALESCE(SUM(jl.debit),0) total_debit,COALESCE(SUM(jl.credit),0) total_credit FROM journal_entries je INNER JOIN users u ON u.id=je.created_by LEFT JOIN journal_entry_lines jl ON jl.journal_entry_id=je.id WHERE je.company_id=:company AND je.entry_date BETWEEN :start AND :end GROUP BY je.id ORDER BY je.entry_date DESC,je.id DESC LIMIT '.$pagination['per_page'].' OFFSET '.$pagination['offset'],['company'=>$financeCompany,'start'=>$start,'end'=>$end]);Response::success($rows);}
    if($financeMethod==='POST'&&$financeId===null){$auth->requirePermission('finance.create');$data=karoor_finance_validate(karoor_finance_input(),['entry_date'=>'required|date:Y-m-d','description'=>'required|string|max_length:500','status'=>'sometimes|in:DRAFT,POSTED','lines'=>'required|list|min:2|max:100','lines.*.chart_account_id'=>'required|integer|min:1','lines.*.description'=>'sometimes|nullable|string|max_length:255','lines.*.debit'=>'sometimes|numeric|min:0','lines.*.credit'=>'sometimes|numeric|min:0']);try{$id=$database->transaction(function(Database$db)use($data,$financeCompany,$financeUser,$auditLogger):int{$debit=0.0;$credit=0.0;foreach($data['lines']as$line){$d=round((float)($line['debit']??0),4);$c=round((float)($line['credit']??0),4);if(($d>0&&$c>0)||($d<=0&&$c<=0))throw new DomainException('Each journal line must contain either a debit or credit.');$account=$db->fetchOne('SELECT id FROM chart_of_accounts WHERE id=:id AND company_id=:company AND allow_manual_entries=1 AND is_active=1 AND deleted_at IS NULL',['id'=>(int)$line['chart_account_id'],'company'=>$financeCompany]);if($account===null)throw new DomainException('A selected account does not allow manual entries.');$debit+=$d;$credit+=$c;}if(abs($debit-$credit)>0.0001)throw new DomainException('Journal debits and credits must balance.');$number=Helpers::nextDocumentNumber($db,$financeCompany,$financeUser['branch_id']===null?null:(int)$financeUser['branch_id'],'JOURNAL',new DateTimeImmutable($data['entry_date']));$id=$db->insert('journal_entries',['company_id'=>$financeCompany,'branch_id'=>$financeUser['branch_id'],'entry_number'=>$number,'entry_date'=>$data['entry_date'],'reference_type'=>'MANUAL','reference_id'=>null,'description'=>$data['description'],'status'=>'DRAFT','created_by'=>(int)$financeUser['id']]);foreach($data['lines']as$line)$db->insert('journal_entry_lines',['journal_entry_id'=>$id,'chart_account_id'=>(int)$line['chart_account_id'],'customer_id'=>null,'supplier_id'=>null,'description'=>$line['description']??null,'debit'=>$line['debit']??0,'credit'=>$line['credit']??0]);if(($data['status']??'DRAFT')==='POSTED')karoor_finance_post($db,$financeUser,['id'=>$id]);$auditLogger->log('CREATE','finance',$id,null,['entry_number'=>$number,'status'=>$data['status']??'DRAFT'],'journal_entries',(int)$financeUser['id'],$financeCompany);return$id;});}catch(DomainException$e){Response::error($e->getMessage(),[],422);}Response::success(karoor_finance_journal_detail($database,$id,$financeCompany),'Journal entry created.',[],201);}
    if($financeMethod==='POST'&&$financeId!==null&&$financeAction==='post'){$auth->requirePermission('finance.post');try{$database->transaction(function(Database$db)use($financeId,$financeCompany,$financeUser,$auditLogger):void{$journal=karoor_finance_journal($db,$financeId,$financeCompany,true);if($journal['status']!=='DRAFT')throw new DomainException('Only draft journals can be posted.');karoor_finance_post($db,$financeUser,$journal);$auditLogger->log('UPDATE','finance',$financeId,['status'=>'DRAFT'],['status'=>'POSTED'],'journal_entries',(int)$financeUser['id'],$financeCompany);});}catch(DomainException$e){Response::error($e->getMessage(),[],422);}Response::success(karoor_finance_journal_detail($database,$financeId,$financeCompany),'Journal posted.');}
    if($financeMethod==='POST'&&$financeId!==null&&$financeAction==='reverse'){$auth->requirePermission('finance.post');try{$newId=$database->transaction(function(Database$db)use($financeId,$financeCompany,$financeUser,$auditLogger):int{$journal=karoor_finance_journal($db,$financeId,$financeCompany,true);if($journal['status']!=='POSTED')throw new DomainException('Only a posted journal can be reversed.');$number=Helpers::nextDocumentNumber($db,$financeCompany,$journal['branch_id']===null?null:(int)$journal['branch_id'],'JOURNAL');$new=$db->insert('journal_entries',['company_id'=>$financeCompany,'branch_id'=>$journal['branch_id'],'entry_number'=>$number,'entry_date'=>date('Y-m-d'),'reference_type'=>'REVERSAL','reference_id'=>$financeId,'description'=>'Reversal: '.$journal['description'],'status'=>'POSTED','posted_at'=>date('Y-m-d H:i:s'),'posted_by'=>(int)$financeUser['id'],'created_by'=>(int)$financeUser['id']]);foreach($db->fetchAll('SELECT * FROM journal_entry_lines WHERE journal_entry_id=:id',['id'=>$financeId])as$line)$db->insert('journal_entry_lines',['journal_entry_id'=>$new,'chart_account_id'=>(int)$line['chart_account_id'],'customer_id'=>$line['customer_id'],'supplier_id'=>$line['supplier_id'],'description'=>'Reversal: '.(string)$line['description'],'debit'=>$line['credit'],'credit'=>$line['debit']]);$db->execute('UPDATE journal_entries SET status=\'REVERSED\',reversed_entry_id=:new WHERE id=:id',['new'=>$new,'id'=>$financeId]);$auditLogger->log('UPDATE','finance',$financeId,['status'=>'POSTED'],['status'=>'REVERSED','reversal_id'=>$new],'journal_entries',(int)$financeUser['id'],$financeCompany);return$new;});}catch(DomainException$e){Response::error($e->getMessage(),[],422);}Response::success(karoor_finance_journal_detail($database,$newId,$financeCompany),'Journal reversed.');}
}

if(in_array($financeResource,['ledger','trial-balance','income-statement','balance-sheet'],true)&&$financeMethod==='GET'){$auth->requirePermission($financeResource==='ledger'?'finance.view':'finance.reports');[$start,$end]=karoor_finance_dates();$params=['company'=>$financeCompany,'start'=>$start,'end'=>$end];$typeClause=match($financeResource){'income-statement'=>" AND coa.account_type IN ('REVENUE','EXPENSE')",'balance-sheet'=>" AND coa.account_type IN ('ASSET','LIABILITY','EQUITY')",default=>''};$rows=$database->fetchAll('SELECT coa.id,coa.code,coa.name,coa.account_type,coa.normal_balance,COALESCE(SUM(CASE WHEN je.id IS NOT NULL THEN jl.debit ELSE 0 END),0) debit,COALESCE(SUM(CASE WHEN je.id IS NOT NULL THEN jl.credit ELSE 0 END),0) credit,CASE WHEN coa.normal_balance=\'DEBIT\' THEN COALESCE(SUM(CASE WHEN je.id IS NOT NULL THEN jl.debit-jl.credit ELSE 0 END),0) ELSE COALESCE(SUM(CASE WHEN je.id IS NOT NULL THEN jl.credit-jl.debit ELSE 0 END),0) END balance FROM chart_of_accounts coa LEFT JOIN journal_entry_lines jl ON jl.chart_account_id=coa.id LEFT JOIN journal_entries je ON je.id=jl.journal_entry_id AND je.status IN (\'POSTED\',\'REVERSED\') AND je.entry_date BETWEEN :start AND :end WHERE coa.company_id=:company AND coa.deleted_at IS NULL'.$typeClause.' GROUP BY coa.id HAVING debit<>0 OR credit<>0 OR balance<>0 ORDER BY coa.code',$params);Response::success($rows,'Financial report loaded.',['start_date'=>$start,'end_date'=>$end]);}
if($financeResource==='cash-flow'&&$financeMethod==='GET'){$auth->requirePermission('finance.reports');[$start,$end]=karoor_finance_dates();$rows=$database->fetchAll('SELECT payment_method,SUM(CASE WHEN direction=\'IN\' THEN amount ELSE 0 END) cash_in,SUM(CASE WHEN direction=\'OUT\' THEN amount ELSE 0 END) cash_out,SUM(CASE WHEN direction=\'IN\' THEN amount ELSE -amount END) net_cash FROM payments WHERE company_id=:company AND DATE(payment_date) BETWEEN :start AND :end AND deleted_at IS NULL GROUP BY payment_method ORDER BY payment_method',['company'=>$financeCompany,'start'=>$start,'end'=>$end]);Response::success($rows,'Cash flow loaded.',['start_date'=>$start,'end_date'=>$end]);}
if(in_array($financeResource,['receivables','payables'],true)&&$financeMethod==='GET'){$auth->requirePermission('finance.reports');$customer=$financeResource==='receivables';$rows=$database->fetchAll($customer?'SELECT c.id,c.customer_code code,c.name,COALESCE(SUM(ct.debit-ct.credit),0) balance FROM customers c LEFT JOIN customer_transactions ct ON ct.customer_id=c.id WHERE c.company_id=:company AND c.deleted_at IS NULL GROUP BY c.id HAVING balance>0 ORDER BY balance DESC':'SELECT s.id,s.supplier_code code,s.name,COALESCE(SUM(st.credit-st.debit),0) balance FROM suppliers s LEFT JOIN supplier_transactions st ON st.supplier_id=s.id WHERE s.company_id=:company AND s.deleted_at IS NULL GROUP BY s.id HAVING balance>0 ORDER BY balance DESC',['company'=>$financeCompany]);Response::success($rows);}
if($financeResource==='payments'&&$financeMethod==='GET'){$auth->requirePermission('finance.view');$pagination=Helpers::pagination();$rows=$database->fetchAll('SELECT p.*,a.name account_name,u.full_name created_by_name FROM payments p INNER JOIN accounts a ON a.id=p.account_id INNER JOIN users u ON u.id=p.created_by WHERE p.company_id=:company AND p.deleted_at IS NULL ORDER BY p.payment_date DESC,p.id DESC LIMIT '.$pagination['per_page'].' OFFSET '.$pagination['offset'],['company'=>$financeCompany]);Response::success($rows);}
Response::notFound('The requested finance endpoint was not found.');
