<?php

declare(strict_types=1);

use Karoor\Core\Database;
use Karoor\Core\Helpers;
use Karoor\Core\Response;
use Karoor\Core\Validator;

if (!defined('KAROOR_BOOTSTRAPPED')) { http_response_code(404); exit; }

$inventoryUser = $auth->requireAuth();
$inventoryCompany = (int) $inventoryUser['company_id'];
$inventoryMethod = Helpers::requestMethod();
$inventoryResource = $apiAction === 'index' ? 'stock' : $apiAction;
$inventoryId = isset($apiSegments[1]) && ctype_digit((string) $apiSegments[1]) ? (int) $apiSegments[1] : null;
$inventorySubAction = $inventoryId === null ? null : ($apiSegments[2] ?? null);

/** @return array<string,mixed> */
function karoor_inventory_input(): array { try { return Helpers::requestData(); } catch (RuntimeException) { Response::error('The request body is invalid.', [], 400); } }
function karoor_inventory_money(mixed $value): float { return round((float) $value, 4); }
function karoor_inventory_validate(array $input, array $rules): array {
    $validator = new Validator($input, $rules);
    if (!$validator->passes()) { Response::validation($validator->errors()); }
    return $validator->validated();
}
function karoor_inventory_company_row(Database $db, string $table, int $id, int $companyId, bool $lock = false): array {
    $allowed = ['products', 'categories', 'warehouses', 'stock_transfers', 'stock_adjustments'];
    if (!in_array($table, $allowed, true)) { throw new RuntimeException('Unsupported inventory table.'); }
    $row = $db->fetchOne('SELECT * FROM ' . Database::quoteIdentifier($table) . ' WHERE id = :id AND company_id = :company_id AND deleted_at IS NULL' . ($lock ? ' FOR UPDATE' : ''), ['id' => $id, 'company_id' => $companyId]);
    if ($row === null) { throw new DomainException('The inventory record was not found.'); }
    return $row;
}
function karoor_inventory_scope(Database $db, int $companyId, int $warehouseId, int $productId): array {
    $row = $db->fetchOne(
        'SELECT p.id AS product_id, p.name, p.track_inventory, p.purchase_price, w.id AS warehouse_id
         FROM products p INNER JOIN warehouses w ON w.id = :warehouse_id AND w.company_id = p.company_id
         WHERE p.id = :product_id AND p.company_id = :company_id AND p.is_active = 1 AND p.deleted_at IS NULL
           AND w.is_active = 1 AND w.deleted_at IS NULL',
        ['warehouse_id' => $warehouseId, 'product_id' => $productId, 'company_id' => $companyId]
    );
    if ($row === null || !(bool) $row['track_inventory']) { throw new DomainException('The selected stock product or warehouse is unavailable.'); }
    return $row;
}
function karoor_inventory_image(array $config): ?string {
    if (!isset($_FILES['image']) || !is_array($_FILES['image']) || ($_FILES['image']['error'] ?? UPLOAD_ERR_NO_FILE) === UPLOAD_ERR_NO_FILE) { return null; }
    $file = $_FILES['image'];
    if (($file['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK || !is_uploaded_file((string) $file['tmp_name'])) { throw new DomainException('The product image upload failed.'); }
    if ((int) $file['size'] > (int) $config['security']['max_upload_bytes']) { throw new DomainException('The product image exceeds the upload size limit.'); }
    $mime = (new finfo(FILEINFO_MIME_TYPE))->file((string) $file['tmp_name']);
    $extension = strtolower(pathinfo((string) $file['name'], PATHINFO_EXTENSION));
    $mimeExtensions = ['image/jpeg' => ['jpg', 'jpeg'], 'image/png' => ['png'], 'image/webp' => ['webp']];
    if (!isset($mimeExtensions[$mime]) || !in_array($extension, $mimeExtensions[$mime], true)) { throw new DomainException('The product image must be a valid JPG, PNG, or WebP file.'); }
    $directory = rtrim((string) $config['paths']['uploads'], '/') . '/products';
    if (!is_dir($directory) && !mkdir($directory, 0750, true) && !is_dir($directory)) { throw new RuntimeException('Unable to prepare the product upload directory.'); }
    $filename = Helpers::uuid() . '.' . ($mime === 'image/jpeg' ? 'jpg' : $extension);
    if (!move_uploaded_file((string) $file['tmp_name'], $directory . '/' . $filename)) { throw new RuntimeException('Unable to store the product image.'); }
    return 'uploads/products/' . $filename;
}
/** @param list<array<string,mixed>> $items */
function karoor_inventory_apply(Database $db, array $user, int $warehouseId, array $items, string $type, string $referenceType, int $referenceId, string $notes, string $at): void {
    foreach ($items as $item) {
        karoor_inventory_scope($db, (int) $user['company_id'], $warehouseId, (int) $item['product_id']);
        $stock = $db->fetchOne('SELECT * FROM warehouse_inventory WHERE warehouse_id = :warehouse_id AND product_id = :product_id FOR UPDATE', ['warehouse_id' => $warehouseId, 'product_id' => (int) $item['product_id']]);
        $before = karoor_inventory_money($stock['quantity'] ?? 0);
        $quantity = karoor_inventory_money($item['quantity']);
        $outgoing = in_array($type, ['ADJUSTMENT_OUT', 'TRANSFER_OUT'], true);
        $after = karoor_inventory_money($before + ($outgoing ? -$quantity : $quantity));
        if ($after < 0) { throw new DomainException('Insufficient stock for an inventory operation.'); }
        $cost = karoor_inventory_money($item['unit_cost'] ?? ($stock['average_cost'] ?? 0));
        $average = $stock === null ? $cost : karoor_inventory_money($stock['average_cost']);
        if (!$outgoing && $after > 0) { $average = karoor_inventory_money((($before * $average) + ($quantity * $cost)) / $after); }
        if ($stock === null) {
            $db->insert('warehouse_inventory', ['warehouse_id' => $warehouseId, 'product_id' => (int) $item['product_id'], 'quantity' => $after, 'reserved_quantity' => 0, 'average_cost' => $average, 'last_movement_at' => $at]);
        } else {
            $db->execute('UPDATE warehouse_inventory SET quantity = :quantity, average_cost = :average_cost, last_movement_at = :at WHERE id = :id', ['quantity' => $after, 'average_cost' => $average, 'at' => $at, 'id' => (int) $stock['id']]);
        }
        $db->insert('stock_movements', ['company_id' => (int) $user['company_id'], 'warehouse_id' => $warehouseId, 'product_id' => (int) $item['product_id'], 'movement_type' => $type, 'quantity' => $quantity, 'quantity_before' => $before, 'quantity_after' => $after, 'unit_cost' => $cost, 'reference_type' => $referenceType, 'reference_id' => $referenceId, 'notes' => $notes, 'movement_at' => $at, 'created_by' => (int) $user['id']]);
    }
}

if ($inventoryResource === 'products') {
    if ($inventoryMethod === 'GET') {
        $auth->requirePermission('products.view');
        if ($inventoryId !== null) {
            $product = karoor_inventory_company_row($database, 'products', $inventoryId, $inventoryCompany);
            $product['stock'] = $database->fetchAll('SELECT wi.*, w.code AS warehouse_code, w.name AS warehouse_name FROM warehouse_inventory wi INNER JOIN warehouses w ON w.id = wi.warehouse_id WHERE wi.product_id = :id AND w.company_id = :company_id AND w.deleted_at IS NULL ORDER BY w.name', ['id' => $inventoryId, 'company_id' => $inventoryCompany]);
            Response::success($product);
        }
        $pagination = Helpers::pagination(); $where = ['p.company_id = :company_id', 'p.deleted_at IS NULL']; $parameters = ['company_id' => $inventoryCompany];
        if (isset($_GET['search']) && trim((string) $_GET['search']) !== '') { $search = '%' . trim((string) $_GET['search']) . '%'; $where[] = '(p.name LIKE :name_search OR p.sku LIKE :sku_search OR p.barcode LIKE :barcode_search)'; $parameters += ['name_search' => $search, 'sku_search' => $search, 'barcode_search' => $search]; }
        foreach (['category_id' => 'p.category_id', 'is_active' => 'p.is_active'] as $key => $column) { if (isset($_GET[$key]) && $_GET[$key] !== '') { $where[] = "$column = :$key"; $parameters[$key] = $_GET[$key]; } }
        $sqlWhere = implode(' AND ', $where); $count = $database->fetchOne('SELECT COUNT(*) total FROM products p WHERE ' . $sqlWhere, $parameters);
        $rows = $database->fetchAll('SELECT p.*, c.name category_name, u.short_name unit, b.name brand_name, t.rate tax_rate, COALESCE(SUM(wi.quantity),0) total_stock FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN units u ON u.id=p.unit_id LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN taxes t ON t.id=p.tax_id LEFT JOIN warehouse_inventory wi ON wi.product_id=p.id WHERE ' . $sqlWhere . ' GROUP BY p.id ORDER BY p.name LIMIT ' . $pagination['per_page'] . ' OFFSET ' . $pagination['offset'], $parameters);
        Response::success($rows, 'Products loaded.', Helpers::paginationMeta((int) ($count['total'] ?? 0), $pagination['page'], $pagination['per_page']));
    }
    if (in_array($inventoryMethod, ['POST', 'PUT', 'PATCH'], true)) {
        $auth->requirePermission($inventoryMethod === 'POST' ? 'inventory.create' : 'inventory.edit');
        $data = karoor_inventory_validate(karoor_inventory_input(), ['sku' => 'required|string|max_length:100', 'barcode' => 'sometimes|nullable|string|max_length:100', 'name' => 'required|string|max_length:190', 'description' => 'sometimes|nullable|string|max_length:10000', 'category_id' => 'sometimes|nullable|integer|min:1', 'brand_id' => 'sometimes|nullable|integer|min:1', 'unit_id' => 'required|integer|min:1', 'tax_id' => 'sometimes|nullable|integer|min:1', 'product_type' => 'sometimes|in:STOCK,SERVICE', 'purchase_price' => 'required|numeric|min:0', 'selling_price' => 'required|numeric|min:0', 'wholesale_price' => 'sometimes|nullable|numeric|min:0', 'minimum_stock' => 'sometimes|numeric|min:0', 'is_active' => 'sometimes|boolean']);
        try {
            $image = karoor_inventory_image($config);
            $id = $database->transaction(function (Database $db) use ($data, $inventoryId, $inventoryCompany, $inventoryUser, $image, $auditLogger): int {
                foreach (['units' => (int) $data['unit_id'], 'categories' => (int) ($data['category_id'] ?? 0), 'brands' => (int) ($data['brand_id'] ?? 0), 'taxes' => (int) ($data['tax_id'] ?? 0)] as $table => $foreignId) { if ($foreignId > 0 && $db->fetchOne('SELECT id FROM ' . Database::quoteIdentifier($table) . ' WHERE id=:id AND company_id=:company_id AND deleted_at IS NULL', ['id' => $foreignId, 'company_id' => $inventoryCompany]) === null) { throw new DomainException('A selected product option is unavailable.'); } }
                $duplicate = $db->fetchOne('SELECT id FROM products WHERE company_id=:company_id AND (sku=:sku OR (barcode IS NOT NULL AND barcode=:barcode)) AND deleted_at IS NULL AND id <> :id', ['company_id' => $inventoryCompany, 'sku' => $data['sku'], 'barcode' => $data['barcode'] ?? '', 'id' => $inventoryId ?? 0]);
                if ($duplicate !== null) { throw new DomainException('The SKU or barcode is already in use.'); }
                $values = ['company_id' => $inventoryCompany, 'category_id' => $data['category_id'] ?? null, 'brand_id' => $data['brand_id'] ?? null, 'unit_id' => (int) $data['unit_id'], 'tax_id' => $data['tax_id'] ?? null, 'sku' => $data['sku'], 'barcode' => $data['barcode'] ?? null, 'name' => $data['name'], 'description' => $data['description'] ?? null, 'product_type' => $data['product_type'] ?? 'STOCK', 'purchase_price' => $data['purchase_price'], 'selling_price' => $data['selling_price'], 'wholesale_price' => $data['wholesale_price'] ?? null, 'minimum_stock' => $data['minimum_stock'] ?? 0, 'track_inventory' => ($data['product_type'] ?? 'STOCK') === 'STOCK' ? 1 : 0, 'is_active' => $data['is_active'] ?? 1];
                if ($image !== null) { $values['image_path'] = $image; }
                if ($inventoryId === null) { $recordId = $db->insert('products', $values); $old = null; } else { $old = karoor_inventory_company_row($db, 'products', $inventoryId, $inventoryCompany, true); $sets=[]; $parameters=['id'=>$inventoryId]; foreach ($values as $key=>$value) { if ($key==='company_id') continue; $sets[]="$key=:$key"; $parameters[$key]=$value; } $db->execute('UPDATE products SET '.implode(',',$sets).' WHERE id=:id', $parameters); $recordId=$inventoryId; }
                $auditLogger->log($inventoryId === null ? 'CREATE' : 'UPDATE', 'inventory', $recordId, $old, $values, 'products', (int) $inventoryUser['id'], $inventoryCompany); return $recordId;
            });
        } catch (DomainException $exception) { Response::error($exception->getMessage(), [], 422); }
        Response::success(karoor_inventory_company_row($database, 'products', $id, $inventoryCompany), $inventoryId === null ? 'Product created.' : 'Product updated.', [], $inventoryId === null ? 201 : 200);
    }
    if ($inventoryMethod === 'DELETE' && $inventoryId !== null) { $auth->requirePermission('inventory.delete'); $updated=$database->execute('UPDATE products SET deleted_at=NOW(),deleted_by=:user WHERE id=:id AND company_id=:company AND deleted_at IS NULL', ['user'=>(int)$inventoryUser['id'],'id'=>$inventoryId,'company'=>$inventoryCompany]); if($updated!==1) Response::notFound(); $auditLogger->log('DELETE','inventory',$inventoryId,null,['deleted'=>true],'products',(int)$inventoryUser['id'],$inventoryCompany); Response::success(null,'Product moved to the recycle bin.'); }
}

if ($inventoryResource === 'categories') {
    if ($inventoryMethod === 'GET') { $auth->requirePermission('inventory.view'); $rows=$database->fetchAll('SELECT c.*,p.name parent_name,(SELECT COUNT(*) FROM products pr WHERE pr.category_id=c.id AND pr.deleted_at IS NULL) product_count FROM categories c LEFT JOIN categories p ON p.id=c.parent_id WHERE c.company_id=:company AND c.deleted_at IS NULL ORDER BY c.sort_order,c.name',['company'=>$inventoryCompany]); Response::success($rows); }
    if (in_array($inventoryMethod,['POST','PUT','PATCH'],true)) { $auth->requirePermission($inventoryMethod==='POST'?'inventory.create':'inventory.edit'); $data=karoor_inventory_validate(karoor_inventory_input(),['name'=>'required|string|max_length:150','parent_id'=>'sometimes|nullable|integer|min:1','description'=>'sometimes|nullable|string|max_length:10000','sort_order'=>'sometimes|integer|min:0','is_active'=>'sometimes|boolean']); try { $id=$database->transaction(function(Database $db) use($data,$inventoryId,$inventoryCompany,$inventoryUser,$auditLogger):int { if(isset($data['parent_id']) && ((int)$data['parent_id']===$inventoryId || $db->fetchOne('SELECT id FROM categories WHERE id=:id AND company_id=:company AND deleted_at IS NULL',['id'=>(int)$data['parent_id'],'company'=>$inventoryCompany])===null)) throw new DomainException('The parent category is unavailable.'); $slug=Helpers::slug((string)$data['name']); $values=['company_id'=>$inventoryCompany,'parent_id'=>$data['parent_id']??null,'name'=>$data['name'],'slug'=>$slug,'description'=>$data['description']??null,'sort_order'=>$data['sort_order']??0,'is_active'=>$data['is_active']??1]; if($inventoryId===null){$record=$db->insert('categories',$values);$old=null;}else{$old=karoor_inventory_company_row($db,'categories',$inventoryId,$inventoryCompany,true);$db->execute('UPDATE categories SET parent_id=:parent,name=:name,slug=:slug,description=:description,sort_order=:sort,is_active=:active WHERE id=:id',['parent'=>$values['parent_id'],'name'=>$values['name'],'slug'=>$slug,'description'=>$values['description'],'sort'=>$values['sort_order'],'active'=>$values['is_active'],'id'=>$inventoryId]);$record=$inventoryId;} $auditLogger->log($inventoryId===null?'CREATE':'UPDATE','inventory',$record,$old,$values,'categories',(int)$inventoryUser['id'],$inventoryCompany);return $record;}); } catch(DomainException $e){Response::error($e->getMessage(),[],422);} Response::success(karoor_inventory_company_row($database,'categories',$id,$inventoryCompany),$inventoryId===null?'Category created.':'Category updated.',[],$inventoryId===null?201:200); }
    if($inventoryMethod==='DELETE'&&$inventoryId!==null){$auth->requirePermission('inventory.delete');$updated=$database->execute('UPDATE categories SET deleted_at=NOW(),deleted_by=:user WHERE id=:id AND company_id=:company AND deleted_at IS NULL',['user'=>(int)$inventoryUser['id'],'id'=>$inventoryId,'company'=>$inventoryCompany]);if($updated!==1)Response::notFound();$auditLogger->log('DELETE','inventory',$inventoryId,null,['deleted'=>true],'categories',(int)$inventoryUser['id'],$inventoryCompany);Response::success(null,'Category moved to the recycle bin.');}
}

if ($inventoryResource === 'warehouses') {
    if($inventoryMethod==='GET'){ $auth->requirePermission('inventory.view'); Response::success($database->fetchAll('SELECT w.*,b.name branch_name,COALESCE(SUM(wi.quantity*wi.average_cost),0) stock_value,COUNT(wi.id) product_count FROM warehouses w LEFT JOIN branches b ON b.id=w.branch_id LEFT JOIN warehouse_inventory wi ON wi.warehouse_id=w.id WHERE w.company_id=:company AND w.deleted_at IS NULL GROUP BY w.id ORDER BY w.is_default DESC,w.name',['company'=>$inventoryCompany])); }
    if(in_array($inventoryMethod,['POST','PUT','PATCH'],true)){ $auth->requirePermission($inventoryMethod==='POST'?'inventory.create':'inventory.edit');$data=karoor_inventory_validate(karoor_inventory_input(),['code'=>'required|string|max_length:30','name'=>'required|string|max_length:150','branch_id'=>'sometimes|nullable|integer|min:1','phone'=>'sometimes|nullable|string|max_length:50','email'=>'sometimes|nullable|email|max_length:190','address'=>'sometimes|nullable|string|max_length:255','is_default'=>'sometimes|boolean','is_active'=>'sometimes|boolean']);try{$id=$database->transaction(function(Database $db)use($data,$inventoryId,$inventoryCompany,$inventoryUser,$auditLogger):int{if(isset($data['branch_id'])&&$data['branch_id']!==null&&$db->fetchOne('SELECT id FROM branches WHERE id=:id AND company_id=:company AND deleted_at IS NULL',['id'=>(int)$data['branch_id'],'company'=>$inventoryCompany])===null)throw new DomainException('The branch is unavailable.');if(($data['is_default']??false))$db->execute('UPDATE warehouses SET is_default=0 WHERE company_id=:company',['company'=>$inventoryCompany]);$values=['company_id'=>$inventoryCompany,'branch_id'=>$data['branch_id']??null,'code'=>$data['code'],'name'=>$data['name'],'phone'=>$data['phone']??null,'email'=>$data['email']??null,'address'=>$data['address']??null,'is_default'=>$data['is_default']??0,'is_active'=>$data['is_active']??1];if($inventoryId===null){$record=$db->insert('warehouses',$values);$old=null;}else{$old=karoor_inventory_company_row($db,'warehouses',$inventoryId,$inventoryCompany,true);$db->execute('UPDATE warehouses SET branch_id=:branch,code=:code,name=:name,phone=:phone,email=:email,address=:address,is_default=:default_flag,is_active=:active WHERE id=:id',['branch'=>$values['branch_id'],'code'=>$values['code'],'name'=>$values['name'],'phone'=>$values['phone'],'email'=>$values['email'],'address'=>$values['address'],'default_flag'=>$values['is_default'],'active'=>$values['is_active'],'id'=>$inventoryId]);$record=$inventoryId;}$auditLogger->log($inventoryId===null?'CREATE':'UPDATE','inventory',$record,$old,$values,'warehouses',(int)$inventoryUser['id'],$inventoryCompany);return $record;});}catch(DomainException $e){Response::error($e->getMessage(),[],422);}Response::success(karoor_inventory_company_row($database,'warehouses',$id,$inventoryCompany),$inventoryId===null?'Warehouse created.':'Warehouse updated.',[],$inventoryId===null?201:200);}
}

if(in_array($inventoryResource,['stock','movements'],true)&&$inventoryMethod==='GET'){ $auth->requirePermission('inventory.view');$pagination=Helpers::pagination();$where=['w.company_id=:company'];$params=['company'=>$inventoryCompany];if(isset($_GET['warehouse_id'])&&$_GET['warehouse_id']!==''){$where[]='w.id=:warehouse';$params['warehouse']=$_GET['warehouse_id'];}if(isset($_GET['product_id'])&&$_GET['product_id']!==''){$where[]='p.id=:product';$params['product']=$_GET['product_id'];}$sqlWhere=implode(' AND ',$where);if($inventoryResource==='stock'){$rows=$database->fetchAll('SELECT wi.*,p.sku,p.barcode,p.name product_name,p.minimum_stock,w.code warehouse_code,w.name warehouse_name,(wi.quantity-wi.reserved_quantity) available_quantity FROM warehouse_inventory wi INNER JOIN products p ON p.id=wi.product_id INNER JOIN warehouses w ON w.id=wi.warehouse_id WHERE '.$sqlWhere.' AND p.deleted_at IS NULL AND w.deleted_at IS NULL ORDER BY p.name LIMIT '.$pagination['per_page'].' OFFSET '.$pagination['offset'],$params);}else{$rows=$database->fetchAll('SELECT sm.*,p.sku,p.name product_name,w.name warehouse_name,u.full_name created_by_name FROM stock_movements sm INNER JOIN products p ON p.id=sm.product_id INNER JOIN warehouses w ON w.id=sm.warehouse_id INNER JOIN users u ON u.id=sm.created_by WHERE '.$sqlWhere.' ORDER BY sm.movement_at DESC,sm.id DESC LIMIT '.$pagination['per_page'].' OFFSET '.$pagination['offset'],$params);}Response::success($rows); }

if($inventoryResource==='adjustments'){
    if($inventoryMethod==='GET'){ $auth->requirePermission('inventory.view');Response::success($database->fetchAll('SELECT sa.*,w.name warehouse_name,u.full_name created_by_name FROM stock_adjustments sa INNER JOIN warehouses w ON w.id=sa.warehouse_id INNER JOIN users u ON u.id=sa.created_by WHERE sa.company_id=:company AND sa.deleted_at IS NULL ORDER BY sa.adjustment_date DESC',['company'=>$inventoryCompany]));}
    if($inventoryMethod==='POST'&&$inventoryId===null){$auth->requirePermission('inventory.adjust');$data=karoor_inventory_validate(karoor_inventory_input(),['warehouse_id'=>'required|integer|min:1','adjustment_type'=>'required|in:IN,OUT','reason'=>'required|string|max_length:255','status'=>'sometimes|in:DRAFT,POSTED','items'=>'required|list|min:1|max:200','items.*.product_id'=>'required|integer|min:1','items.*.quantity'=>'required|numeric|min:0.0001','items.*.unit_cost'=>'sometimes|numeric|min:0']);try{$id=$database->transaction(function(Database $db)use($data,$inventoryCompany,$inventoryUser,$auditLogger):int{$at=date('Y-m-d H:i:s');$number=Helpers::nextDocumentNumber($db,$inventoryCompany,$inventoryUser['branch_id']===null?null:(int)$inventoryUser['branch_id'],'ADJUSTMENT');$id=$db->insert('stock_adjustments',['company_id'=>$inventoryCompany,'warehouse_id'=>(int)$data['warehouse_id'],'adjustment_number'=>$number,'adjustment_date'=>$at,'adjustment_type'=>$data['adjustment_type'],'reason'=>$data['reason'],'status'=>'DRAFT','created_by'=>(int)$inventoryUser['id']]);foreach($data['items']as$item)$db->insert('stock_adjustment_items',['stock_adjustment_id'=>$id,'product_id'=>(int)$item['product_id'],'quantity'=>$item['quantity'],'unit_cost'=>$item['unit_cost']??0]);if(($data['status']??'DRAFT')==='POSTED'){karoor_inventory_apply($db,$inventoryUser,(int)$data['warehouse_id'],$data['items'],'ADJUSTMENT_'.$data['adjustment_type'],'ADJUSTMENT',$id,$data['reason'],$at);$db->execute('UPDATE stock_adjustments SET status=\'POSTED\',approved_by=:user,approved_at=:at WHERE id=:id',['user'=>(int)$inventoryUser['id'],'at'=>$at,'id'=>$id]);}$auditLogger->log('STOCK_ADJUSTMENT','inventory',$id,null,['number'=>$number,'status'=>$data['status']??'DRAFT'],'stock_adjustments',(int)$inventoryUser['id'],$inventoryCompany);return $id;});}catch(DomainException $e){Response::error($e->getMessage(),[],422);}Response::success(karoor_inventory_company_row($database,'stock_adjustments',$id,$inventoryCompany),'Stock adjustment created.',[],201);}
    if($inventoryMethod==='POST'&&$inventoryId!==null&&$inventorySubAction==='post'){$auth->requirePermission('inventory.adjust');try{$database->transaction(function(Database $db)use($inventoryId,$inventoryCompany,$inventoryUser,$auditLogger):void{$row=karoor_inventory_company_row($db,'stock_adjustments',$inventoryId,$inventoryCompany,true);if($row['status']!=='DRAFT')throw new DomainException('Only a draft adjustment can be posted.');$items=$db->fetchAll('SELECT product_id,quantity,unit_cost FROM stock_adjustment_items WHERE stock_adjustment_id=:id',['id'=>$inventoryId]);$at=date('Y-m-d H:i:s');karoor_inventory_apply($db,$inventoryUser,(int)$row['warehouse_id'],$items,'ADJUSTMENT_'.$row['adjustment_type'],'ADJUSTMENT',$inventoryId,(string)$row['reason'],$at);$db->execute('UPDATE stock_adjustments SET status=\'POSTED\',approved_by=:user,approved_at=:at WHERE id=:id',['user'=>(int)$inventoryUser['id'],'at'=>$at,'id'=>$inventoryId]);$auditLogger->log('STOCK_ADJUSTMENT','inventory',$inventoryId,['status'=>'DRAFT'],['status'=>'POSTED'],'stock_adjustments',(int)$inventoryUser['id'],$inventoryCompany);});}catch(DomainException$e){Response::error($e->getMessage(),[],422);}Response::success(karoor_inventory_company_row($database,'stock_adjustments',$inventoryId,$inventoryCompany),'Adjustment posted.');}
}

if($inventoryResource==='transfers'){
    if($inventoryMethod==='GET'){ $auth->requirePermission('inventory.view');Response::success($database->fetchAll('SELECT st.*,fw.name from_warehouse,tw.name to_warehouse,u.full_name requested_by_name FROM stock_transfers st INNER JOIN warehouses fw ON fw.id=st.from_warehouse_id INNER JOIN warehouses tw ON tw.id=st.to_warehouse_id INNER JOIN users u ON u.id=st.requested_by WHERE st.company_id=:company AND st.deleted_at IS NULL ORDER BY st.transfer_date DESC',['company'=>$inventoryCompany]));}
    if($inventoryMethod==='POST'&&$inventoryId===null){$auth->requirePermission('inventory.transfer');$data=karoor_inventory_validate(karoor_inventory_input(),['from_warehouse_id'=>'required|integer|min:1','to_warehouse_id'=>'required|integer|min:1','notes'=>'sometimes|nullable|string|max_length:5000','items'=>'required|list|min:1|max:200','items.*.product_id'=>'required|integer|min:1','items.*.quantity'=>'required|numeric|min:0.0001']);if((int)$data['from_warehouse_id']===(int)$data['to_warehouse_id'])Response::validation(['to_warehouse_id'=>['Warehouses must be different.']]);try{$id=$database->transaction(function(Database$db)use($data,$inventoryCompany,$inventoryUser,$auditLogger):int{foreach([(int)$data['from_warehouse_id'],(int)$data['to_warehouse_id']]as$warehouse)if($db->fetchOne('SELECT id FROM warehouses WHERE id=:id AND company_id=:company AND deleted_at IS NULL',['id'=>$warehouse,'company'=>$inventoryCompany])===null)throw new DomainException('A selected warehouse is unavailable.');$number=Helpers::nextDocumentNumber($db,$inventoryCompany,$inventoryUser['branch_id']===null?null:(int)$inventoryUser['branch_id'],'TRANSFER');$id=$db->insert('stock_transfers',['company_id'=>$inventoryCompany,'transfer_number'=>$number,'from_warehouse_id'=>(int)$data['from_warehouse_id'],'to_warehouse_id'=>(int)$data['to_warehouse_id'],'transfer_date'=>date('Y-m-d H:i:s'),'status'=>'PENDING','notes'=>$data['notes']??null,'requested_by'=>(int)$inventoryUser['id']]);foreach($data['items']as$item){$scope=karoor_inventory_scope($db,$inventoryCompany,(int)$data['from_warehouse_id'],(int)$item['product_id']);$stock=$db->fetchOne('SELECT average_cost FROM warehouse_inventory WHERE warehouse_id=:warehouse AND product_id=:product',['warehouse'=>(int)$data['from_warehouse_id'],'product'=>(int)$scope['product_id']]);$db->insert('stock_transfer_items',['stock_transfer_id'=>$id,'product_id'=>(int)$item['product_id'],'quantity'=>$item['quantity'],'received_quantity'=>0,'unit_cost'=>$stock['average_cost']??$scope['purchase_price']]);}$auditLogger->log('STOCK_TRANSFER','inventory',$id,null,['number'=>$number,'status'=>'PENDING'],'stock_transfers',(int)$inventoryUser['id'],$inventoryCompany);return$id;});}catch(DomainException$e){Response::error($e->getMessage(),[],422);}Response::success(karoor_inventory_company_row($database,'stock_transfers',$id,$inventoryCompany),'Stock transfer created.',[],201);}
    if($inventoryMethod==='POST'&&$inventoryId!==null&&in_array($inventorySubAction,['approve','complete'],true)){ $auth->requirePermission('inventory.transfer_approve');try{$database->transaction(function(Database$db)use($inventoryId,$inventorySubAction,$inventoryCompany,$inventoryUser,$auditLogger):void{$row=karoor_inventory_company_row($db,'stock_transfers',$inventoryId,$inventoryCompany,true);if($inventorySubAction==='approve'){if($row['status']!=='PENDING')throw new DomainException('Only a pending transfer can be approved.');$db->execute('UPDATE stock_transfers SET status=\'APPROVED\',approved_by=:user,approved_at=NOW() WHERE id=:id',['user'=>(int)$inventoryUser['id'],'id'=>$inventoryId]);}else{if(!in_array($row['status'],['APPROVED','IN_TRANSIT'],true))throw new DomainException('Approve the transfer before completion.');$items=$db->fetchAll('SELECT product_id,quantity,unit_cost FROM stock_transfer_items WHERE stock_transfer_id=:id',['id'=>$inventoryId]);$at=date('Y-m-d H:i:s');karoor_inventory_apply($db,$inventoryUser,(int)$row['from_warehouse_id'],$items,'TRANSFER_OUT','TRANSFER',$inventoryId,'Transfer '.$row['transfer_number'],$at);karoor_inventory_apply($db,$inventoryUser,(int)$row['to_warehouse_id'],$items,'TRANSFER_IN','TRANSFER',$inventoryId,'Transfer '.$row['transfer_number'],$at);$db->execute('UPDATE stock_transfer_items SET received_quantity=quantity WHERE stock_transfer_id=:id',['id'=>$inventoryId]);$db->execute('UPDATE stock_transfers SET status=\'COMPLETED\',completed_by=:user,completed_at=:at WHERE id=:id',['user'=>(int)$inventoryUser['id'],'at'=>$at,'id'=>$inventoryId]);}$auditLogger->log('STOCK_TRANSFER','inventory',$inventoryId,['status'=>$row['status']],['status'=>$inventorySubAction==='approve'?'APPROVED':'COMPLETED'],'stock_transfers',(int)$inventoryUser['id'],$inventoryCompany);});}catch(DomainException$e){Response::error($e->getMessage(),[],422);}Response::success(karoor_inventory_company_row($database,'stock_transfers',$inventoryId,$inventoryCompany),'Transfer '.($inventorySubAction==='approve'?'approved.':'completed.')); }
}

Response::notFound('The requested inventory endpoint was not found.');
