<?php

declare(strict_types=1);

use Karoor\Core\Helpers;
use Karoor\Core\Response;

if(!defined('KAROOR_BOOTSTRAPPED')){http_response_code(404);exit;}
$auth->requirePermission('reports.view');
if(Helpers::requestMethod()!=='GET'){header('Allow: GET');Response::error('Reports only accept GET requests.',[],405);}
$reportUser=$auth->requireAuth();$reportCompany=(int)$reportUser['company_id'];$reportResource=$apiAction==='index'?(string)($_GET['report']??'sales'):$apiAction;$reportView=is_string($_GET['view']??null)?$_GET['view']:'summary';
function karoor_report_date(string$key,string$fallback):string{$value=is_string($_GET[$key]??null)?$_GET[$key]:$fallback;$date=DateTimeImmutable::createFromFormat('!Y-m-d',$value);if($date===false||$date->format('Y-m-d')!==$value)Response::validation([$key=>['A valid Y-m-d date is required.']]);return$value;}
function karoor_report_output(array$rows,array$meta=[]):never{if(strtolower((string)($_GET['format']??''))==='csv'){global$auth;$auth->requirePermission('reports.export');$filename='karoor-report-'.date('Ymd-His').'.csv';header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="'.$filename.'"');$stream=fopen('php://output','wb');if($stream===false)Response::error('Unable to create the report export.',[],500);if($rows!==[])fputcsv($stream,array_keys($rows[0]));foreach($rows as$row)fputcsv($stream,array_map(static fn($value)=>is_scalar($value)||$value===null?$value:json_encode($value),$row));fclose($stream);exit;}Response::success($rows,'Report loaded.',$meta);}
$start=karoor_report_date('start_date',date('Y-m-01'));$end=karoor_report_date('end_date',date('Y-m-d'));if($start>$end)Response::validation(['date_range'=>['The start date must not follow the end date.']]);$params=['company'=>$reportCompany,'start'=>$start,'end'=>$end];$warehouse='';if(isset($_GET['warehouse_id'])&&$_GET['warehouse_id']!==''){$warehouse=' AND %s.warehouse_id=:warehouse';$params['warehouse']=$_GET['warehouse_id'];}

if($reportResource==='sales'){$group=match($reportView){'daily'=>'DATE(s.sale_date)','monthly'=>"DATE_FORMAT(s.sale_date,'%Y-%m')",'cashier'=>'u.full_name','salesperson'=>'u.full_name','product'=>'si.product_name','category'=>"COALESCE(c.name,'Uncategorized')",'customer'=>"COALESCE(cu.name,'Walk-in')",default=>'DATE(s.sale_date)'};$joins=in_array($reportView,['product','category'],true)?' INNER JOIN sale_items si ON si.sale_id=s.id INNER JOIN products p ON p.id=si.product_id LEFT JOIN categories c ON c.id=p.category_id ':'';$joins.=' INNER JOIN users u ON u.id=s.salesperson_id LEFT JOIN customers cu ON cu.id=s.customer_id ';$amount=in_array($reportView,['product','category'],true)?'SUM(si.line_total)':'SUM(s.total_amount)';$quantity=in_array($reportView,['product','category'],true)?'SUM(si.quantity)':'COUNT(s.id)';$rows=$database->fetchAll('SELECT '.$group.' label,'.$quantity.' quantity,'.$amount.' total FROM sales s'.$joins.' WHERE s.company_id=:company AND s.status=\'COMPLETED\' AND s.deleted_at IS NULL AND DATE(s.sale_date) BETWEEN :start AND :end'.sprintf($warehouse,'s').' GROUP BY '.$group.' ORDER BY total DESC',$params);karoor_report_output($rows,['start_date'=>$start,'end_date'=>$end,'view'=>$reportView]);}
if($reportResource==='purchases'){$group=match($reportView){'monthly'=>"DATE_FORMAT(p.purchase_date,'%Y-%m')",'supplier'=>'s.name','product'=>'pi.product_name',default=>'DATE(p.purchase_date)'};$joins=' INNER JOIN suppliers s ON s.id=p.supplier_id '.($reportView==='product'?' INNER JOIN purchase_items pi ON pi.purchase_id=p.id ':'');$amount=$reportView==='product'?'SUM(pi.line_total)':'SUM(p.total_amount)';$quantity=$reportView==='product'?'SUM(pi.quantity)':'COUNT(p.id)';$rows=$database->fetchAll('SELECT '.$group.' label,'.$quantity.' quantity,'.$amount.' total FROM purchases p'.$joins.' WHERE p.company_id=:company AND p.status=\'RECEIVED\' AND p.deleted_at IS NULL AND DATE(p.purchase_date) BETWEEN :start AND :end'.sprintf($warehouse,'p').' GROUP BY '.$group.' ORDER BY total DESC',$params);karoor_report_output($rows,['start_date'=>$start,'end_date'=>$end,'view'=>$reportView]);}
if($reportResource==='inventory'){$params=['company'=>$reportCompany];$warehouseClause='';$transferWarehouse='';if(isset($_GET['warehouse_id'])&&$_GET['warehouse_id']!==''){$warehouseClause=' AND w.id=:warehouse';$transferWarehouse=' AND (st.from_warehouse_id=:warehouse OR st.to_warehouse_id=:warehouse_two)';$params['warehouse']=$_GET['warehouse_id'];$params['warehouse_two']=$_GET['warehouse_id'];}$queryParams=$params;if($reportView!=='transfers')unset($queryParams['warehouse_two']);$rows=match($reportView){'low-stock'=>$database->fetchAll('SELECT p.id,p.sku,p.name,p.minimum_stock,COALESCE(SUM(wi.quantity-wi.reserved_quantity),0) available_quantity FROM products p LEFT JOIN warehouse_inventory wi ON wi.product_id=p.id LEFT JOIN warehouses w ON w.id=wi.warehouse_id WHERE p.company_id=:company AND p.track_inventory=1 AND p.deleted_at IS NULL'.$warehouseClause.' GROUP BY p.id HAVING available_quantity<=p.minimum_stock ORDER BY available_quantity',$queryParams),'movements'=>$database->fetchAll('SELECT sm.movement_at,sm.movement_type,p.sku,p.name product,w.name warehouse,sm.quantity,sm.quantity_before,sm.quantity_after,sm.unit_cost,sm.reference_type,sm.reference_id FROM stock_movements sm INNER JOIN products p ON p.id=sm.product_id INNER JOIN warehouses w ON w.id=sm.warehouse_id WHERE sm.company_id=:company'.$warehouseClause.' ORDER BY sm.movement_at DESC LIMIT 500',$queryParams),'transfers'=>$database->fetchAll('SELECT st.transfer_number,st.transfer_date,st.status,fw.name source,tw.name destination,SUM(sti.quantity) quantity FROM stock_transfers st INNER JOIN warehouses fw ON fw.id=st.from_warehouse_id INNER JOIN warehouses tw ON tw.id=st.to_warehouse_id INNER JOIN stock_transfer_items sti ON sti.stock_transfer_id=st.id WHERE st.company_id=:company AND st.deleted_at IS NULL'.$transferWarehouse.' GROUP BY st.id ORDER BY st.transfer_date DESC',$queryParams),default=>$database->fetchAll('SELECT w.name warehouse,p.sku,p.name product,wi.quantity,wi.reserved_quantity,wi.average_cost,(wi.quantity*wi.average_cost) stock_value FROM warehouse_inventory wi INNER JOIN warehouses w ON w.id=wi.warehouse_id INNER JOIN products p ON p.id=wi.product_id WHERE w.company_id=:company AND w.deleted_at IS NULL AND p.deleted_at IS NULL'.$warehouseClause.' ORDER BY w.name,p.name',$queryParams)};karoor_report_output($rows,['view'=>$reportView]);}
if($reportResource==='finance'){$auth->requirePermission('finance.reports');$financeParams=['company'=>$reportCompany,'start'=>$start,'end'=>$end];$type=match($reportView){'income-statement'=>" AND coa.account_type IN ('REVENUE','EXPENSE')",'balance-sheet'=>" AND coa.account_type IN ('ASSET','LIABILITY','EQUITY')",default=>''};if($reportView==='expenses'){$rows=$database->fetchAll('SELECT e.expense_date,e.expense_number,ec.name category,e.description,e.payment_method,e.amount FROM expenses e INNER JOIN expense_categories ec ON ec.id=e.expense_category_id WHERE e.company_id=:company AND e.expense_date BETWEEN :start AND :end AND e.deleted_at IS NULL ORDER BY e.expense_date DESC',$financeParams);}elseif(in_array($reportView,['receivables','payables'],true)){$rows=$database->fetchAll($reportView==='receivables'?'SELECT c.customer_code code,c.name,COALESCE(SUM(ct.debit-ct.credit),0) balance FROM customers c LEFT JOIN customer_transactions ct ON ct.customer_id=c.id WHERE c.company_id=:company AND c.deleted_at IS NULL GROUP BY c.id HAVING balance>0 ORDER BY balance DESC':'SELECT s.supplier_code code,s.name,COALESCE(SUM(st.credit-st.debit),0) balance FROM suppliers s LEFT JOIN supplier_transactions st ON st.supplier_id=s.id WHERE s.company_id=:company AND s.deleted_at IS NULL GROUP BY s.id HAVING balance>0 ORDER BY balance DESC',['company'=>$reportCompany]);}else{$rows=$database->fetchAll('SELECT coa.code,coa.name,coa.account_type,SUM(jl.debit) debit,SUM(jl.credit) credit,CASE WHEN coa.normal_balance=\'DEBIT\' THEN SUM(jl.debit-jl.credit) ELSE SUM(jl.credit-jl.debit) END balance FROM chart_of_accounts coa INNER JOIN journal_entry_lines jl ON jl.chart_account_id=coa.id INNER JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE coa.company_id=:company AND je.status IN (\'POSTED\',\'REVERSED\') AND je.entry_date BETWEEN :start AND :end'.$type.' GROUP BY coa.id ORDER BY coa.code',$financeParams);}karoor_report_output($rows,['start_date'=>$start,'end_date'=>$end,'view'=>$reportView]);}
if($reportResource==='hr'){$params=['company'=>$reportCompany,'start'=>$start,'end'=>$end];$rows=match($reportView){'attendance'=>$database->fetchAll('SELECT a.attendance_date,e.employee_number,e.full_name,a.check_in,a.check_out,a.status,a.notes FROM attendance a INNER JOIN employees e ON e.id=a.employee_id WHERE a.company_id=:company AND a.attendance_date BETWEEN :start AND :end ORDER BY a.attendance_date DESC,e.full_name',$params),'leave'=>$database->fetchAll('SELECT e.employee_number,e.full_name,lt.name leave_type,lr.start_date,lr.end_date,lr.total_days,lr.status,lr.reason FROM leave_requests lr INNER JOIN employees e ON e.id=lr.employee_id INNER JOIN leave_types lt ON lt.id=lr.leave_type_id WHERE lr.company_id=:company AND lr.start_date<=:end AND lr.end_date>=:start ORDER BY lr.start_date DESC',$params),'payroll'=>$database->fetchAll('SELECT p.payroll_month,p.status,SUM(p.net_salary) net_salary,SUM(p.gross_salary) gross_salary,COUNT(*) employees FROM payroll p WHERE p.company_id=:company AND p.payroll_month BETWEEN :start AND :end AND p.deleted_at IS NULL GROUP BY p.payroll_month,p.status ORDER BY p.payroll_month DESC',$params),default=>$database->fetchAll('SELECT e.employee_number,e.full_name,d.name department,e.position,e.hire_date,e.base_salary,e.status FROM employees e LEFT JOIN departments d ON d.id=e.department_id WHERE e.company_id=:company AND e.deleted_at IS NULL ORDER BY e.full_name',['company'=>$reportCompany])};karoor_report_output($rows,['view'=>$reportView]);}
if($reportResource==='profit'){$rows=$database->fetchAll('SELECT sales.report_date,sales.gross_profit,COALESCE(expenses.total,0) expenses,sales.gross_profit-COALESCE(expenses.total,0) net_profit FROM (SELECT DATE(s.sale_date) report_date,SUM((si.line_total-si.tax_amount)-(si.quantity*si.cost_price)) gross_profit FROM sales s INNER JOIN sale_items si ON si.sale_id=s.id WHERE s.company_id=:company AND s.status=\'COMPLETED\' AND s.deleted_at IS NULL AND DATE(s.sale_date) BETWEEN :start AND :end GROUP BY DATE(s.sale_date)) sales LEFT JOIN (SELECT e.expense_date report_date,SUM(e.amount) total FROM expenses e WHERE e.company_id=:expense_company AND e.deleted_at IS NULL AND e.expense_date BETWEEN :start AND :end GROUP BY e.expense_date) expenses ON expenses.report_date=sales.report_date ORDER BY sales.report_date',['company'=>$reportCompany,'expense_company'=>$reportCompany,'start'=>$start,'end'=>$end]);karoor_report_output($rows,['start_date'=>$start,'end_date'=>$end]);}
Response::notFound('The requested report was not found.');
