<?php

declare(strict_types=1);

use Karoor\Core\Helpers;

$canCustomers = $auth->can('customers.view');
$canSuppliers = $auth->can('suppliers.view');
$partyView = is_string($_GET['view'] ?? null) ? $_GET['view'] : ($canCustomers ? 'customers' : 'suppliers');
if (!in_array($partyView, ['customers','suppliers'], true) || ($partyView === 'customers' && !$canCustomers) || ($partyView === 'suppliers' && !$canSuppliers)) $partyView = $canCustomers ? 'customers' : 'suppliers';
$isCustomer = $partyView === 'customers';
$partyLabel = $isCustomer ? 'Customers' : 'Suppliers';
$pageTitle = $partyLabel;
$pageDescription = $isCustomer ? 'Customer profiles, credit limits, balances, sales, and payment history.' : 'Supplier profiles, balances, purchases, and payment history.';
$breadcrumbs = ['Parties', $partyLabel];
$canCreate = $auth->can($isCustomer ? 'customers.create' : 'suppliers.create');
$pageActions = static function () use ($canCreate, $isCustomer): void { if ($canCreate) echo '<button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#newPartyModal"><i class="fa-solid fa-plus" aria-hidden="true"></i> Add ' . ($isCustomer ? 'customer' : 'supplier') . '</button>'; };
require __DIR__ . '/../layouts/header.php';
?>

<nav class="nav nav-pills mb-4" aria-label="Party type"><?php if($canCustomers):?><a class="nav-link<?= $isCustomer?' active':'' ?>" href="<?= Helpers::escape(Helpers::appPath($config,'/contacts?view=customers')) ?>"><i class="fa-solid fa-users" aria-hidden="true"></i> Customers</a><?php endif;?><?php if($canSuppliers):?><a class="nav-link<?= !$isCustomer?' active':'' ?>" href="<?= Helpers::escape(Helpers::appPath($config,'/contacts?view=suppliers')) ?>"><i class="fa-solid fa-truck-field" aria-hidden="true"></i> Suppliers</a><?php endif;?></nav>

<section class="surface-card">
 <div class="card-header-row flex-wrap gap-3"><div><h2><?= Helpers::escape($partyLabel) ?></h2><p><span data-table-total="partyTable">0</span> active and archived-status records</p></div><div class="input-group" style="max-width:360px"><span class="input-group-text"><i class="fa-solid fa-magnifying-glass" aria-hidden="true"></i></span><label class="visually-hidden" for="partySearch">Search <?= Helpers::escape(strtolower($partyLabel)) ?></label><input class="form-control" id="partySearch" data-table-search="partyTable" type="search" placeholder="Name, code, or phone…"></div></div>
 <div class="table-responsive"><table class="table align-middle mb-0" id="partyTable" data-api-table data-endpoint="<?= Helpers::escape($partyView) ?>" data-party-type="<?= Helpers::escape($partyView) ?>" data-currency="<?= Helpers::escape((string)($currentUser['currency_code']??$config['app']['currency'])) ?>"><thead><tr><th data-field="<?= $isCustomer?'customer_code':'supplier_code' ?>">Code</th><th data-field="name">Name</th><th data-field="contact_person">Contact person</th><th data-field="phone">Phone</th><th data-field="email">Email</th><?php if($isCustomer):?><th data-field="credit_limit" data-format="currency">Credit limit</th><?php endif;?><th data-field="balance" data-format="currency">Balance</th><th data-field="is_active" data-format="boolean">Active</th><th data-field="id">Actions</th></tr></thead><tbody></tbody></table></div>
 <div class="card-body-pad d-flex justify-content-between align-items-center"><span class="text-secondary">Page <span data-table-current="partyTable">1</span> of <span data-table-last="partyTable">1</span></span><div class="btn-group"><button class="btn btn-outline-secondary" type="button" data-table-page="partyTable" data-page="previous">Previous</button><button class="btn btn-outline-secondary" type="button" data-table-page="partyTable" data-page="next">Next</button></div></div>
</section>

<?php if($canCreate):?><div class="modal fade" id="newPartyModal" tabindex="-1" aria-labelledby="newPartyTitle" aria-hidden="true"><div class="modal-dialog modal-lg"><div class="modal-content"><form data-api-form data-endpoint="<?= Helpers::escape($partyView) ?>" data-method="POST" data-success-redirect="<?= Helpers::escape(Helpers::appPath($config,'/contacts?view='.$partyView)) ?>"><div class="modal-header"><h2 class="modal-title fs-5" id="newPartyTitle">Add <?= $isCustomer?'customer':'supplier' ?></h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-4"><label class="form-label" for="partyCode">Code <span class="text-secondary">(optional)</span></label><input class="form-control" id="partyCode" name="<?= $isCustomer?'customer_code':'supplier_code' ?>" maxlength="40"></div><div class="col-md-8"><label class="form-label" for="partyName">Name</label><input class="form-control" id="partyName" name="name" required maxlength="190"></div><div class="col-md-6"><label class="form-label" for="partyContact">Contact person</label><input class="form-control" id="partyContact" name="contact_person" maxlength="190"></div><div class="col-md-6"><label class="form-label" for="partyPhone">Phone</label><input class="form-control" id="partyPhone" name="phone" maxlength="50"></div><div class="col-md-6"><label class="form-label" for="partyEmail">Email</label><input class="form-control" id="partyEmail" name="email" type="email" maxlength="190"></div><div class="col-md-6"><label class="form-label" for="partyTax">Tax number</label><input class="form-control" id="partyTax" name="tax_number" maxlength="100"></div><div class="col-md-4"><label class="form-label" for="partyCity">City</label><input class="form-control" id="partyCity" name="city" maxlength="100"></div><div class="col-md-8"><label class="form-label" for="partyAddress">Address</label><input class="form-control" id="partyAddress" name="address" maxlength="255"></div><?php if($isCustomer):?><div class="col-md-6"><label class="form-label" for="creditLimit">Credit limit</label><input class="form-control" id="creditLimit" name="credit_limit" type="number" min="0" step="0.01" value="0"></div><?php endif;?><div class="col-md-6"><label class="form-label" for="openingBalance">Opening balance</label><input class="form-control" id="openingBalance" name="opening_balance" type="number" min="0" step="0.01" value="0"></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Save <?= $isCustomer?'customer':'supplier' ?></button></div></form></div></div></div><?php endif;?>

<div class="modal fade" id="partyDetailModal" tabindex="-1" aria-labelledby="partyDetailTitle" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><div><h2 class="modal-title fs-5" id="partyDetailTitle">Party details</h2><span class="text-secondary" data-party-contact></span></div><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><div class="row g-3 mb-4"><div class="col-md-4"><div class="surface-card card-body-pad"><span class="text-secondary">Current balance</span><strong class="d-block fs-4" data-party-balance>—</strong></div></div><div class="col-md-8"><div class="surface-card card-body-pad"><span class="text-secondary">Address</span><strong class="d-block" data-party-address>—</strong></div></div></div><h3 class="fs-6">Ledger</h3><div class="table-responsive"><table class="table"><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Debit</th><th>Credit</th></tr></thead><tbody data-party-ledger></tbody></table></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Close</button></div></div></div></div>

<?php require __DIR__ . '/../layouts/footer.php'; ?>
