<?php
declare(strict_types=1);
use Karoor\Core\Helpers;
$pageTitle='Expenses';$pageDescription='Record operating costs with automatic payment and journal entries.';$breadcrumbs=[['label'=>'Operations'], 'Expenses'];$companyId=(int)$currentUser['company_id'];
$categories=$database->fetchAll('SELECT id,name FROM expense_categories WHERE company_id=:company AND is_active=1 AND deleted_at IS NULL ORDER BY name',['company'=>$companyId]);
$accounts=$database->fetchAll('SELECT id,name,account_kind FROM accounts WHERE company_id=:company AND is_active=1 AND deleted_at IS NULL ORDER BY name',['company'=>$companyId]);
$expenseAccounts=$database->fetchAll('SELECT id,code,name FROM chart_of_accounts WHERE company_id=:company AND account_type=\'EXPENSE\' AND is_active=1 AND deleted_at IS NULL ORDER BY code',['company'=>$companyId]);
$canCreate=$auth->can('expenses.create');$pageActions=static function()use($canCreate):void{if($canCreate)echo '<div class="btn-group"><button class="btn btn-outline-primary" type="button" data-bs-toggle="modal" data-bs-target="#categoryModal">New category</button><button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#expenseModal"><i class="fa-solid fa-plus" aria-hidden="true"></i> Record expense</button></div>';};
require __DIR__.'/../layouts/header.php';
?>
<section class="surface-card">
 <div class="card-header-row"><div><h2>Expense register</h2><p>Every non-credit expense posts a cash payment and balanced accounting entry.</p></div></div>
 <form class="card-body-pad border-bottom row g-2 align-items-end" data-table-filters="expenseTable"><div class="col-md-3"><label class="form-label" for="expenseCategoryFilter">Category</label><select class="form-select" id="expenseCategoryFilter" name="expense_category_id"><option value="">All categories</option><?php foreach($categories as$c):?><option value="<?= (int)$c['id'] ?>"><?= Helpers::escape($c['name']) ?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label" for="expenseMethodFilter">Method</label><select class="form-select" id="expenseMethodFilter" name="payment_method"><option value="">All</option><option>CASH</option><option>BANK</option><option>MOBILE_MONEY</option><option>CREDIT</option><option>OTHER</option></select></div><div class="col-md-2"><label class="form-label" for="expenseStart">From</label><input class="form-control" id="expenseStart" name="start_date" type="date" value="<?= date('Y-m-01') ?>"></div><div class="col-md-2"><label class="form-label" for="expenseEnd">To</label><input class="form-control" id="expenseEnd" name="end_date" type="date" value="<?= date('Y-m-d') ?>"></div><div class="col-md-3 d-flex gap-2"><button class="btn btn-outline-primary" type="submit">Apply</button><button class="btn btn-outline-secondary" type="reset">Reset</button></div></form>
 <div class="table-responsive"><table class="table align-middle mb-0" id="expenseTable" data-api-table data-endpoint="expenses"><thead><tr><th data-field="expense_number">Expense</th><th data-field="expense_date" data-format="date">Date</th><th data-field="category_name">Category</th><th data-field="description">Description</th><th data-field="payment_method" data-format="status">Method</th><th data-field="account_name">Account</th><th data-field="amount" data-format="currency">Amount</th><?php if($auth->can('expenses.delete')):?><th data-field="id" data-format="actions">Actions</th><?php endif;?></tr></thead><tbody></tbody></table></div>
 <div class="card-body-pad d-flex justify-content-end gap-2"><button class="btn btn-outline-secondary" type="button" data-table-page="expenseTable" data-page="previous">Previous</button><button class="btn btn-outline-secondary" type="button" data-table-page="expenseTable" data-page="next">Next</button></div>
</section>
<?php if($canCreate):?><div class="modal fade" id="expenseModal" tabindex="-1" aria-labelledby="expenseTitle" aria-hidden="true"><div class="modal-dialog modal-lg"><div class="modal-content"><form data-api-form data-endpoint="expenses" data-method="POST" data-encoding="multipart" data-success-redirect="<?= Helpers::escape(Helpers::appPath($config,'/expenses')) ?>"><div class="modal-header"><h2 class="modal-title fs-5" id="expenseTitle">Record expense</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label" for="expenseCategory">Category</label><select class="form-select" id="expenseCategory" name="expense_category_id" required><option value="">Select category</option><?php foreach($categories as$c):?><option value="<?= (int)$c['id'] ?>"><?= Helpers::escape($c['name']) ?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label" for="expenseAccount">Payment account</label><select class="form-select" id="expenseAccount" name="account_id" required><option value="">Select account</option><?php foreach($accounts as$a):?><option value="<?= (int)$a['id'] ?>"><?= Helpers::escape($a['name'].' · '.$a['account_kind']) ?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label" for="expenseDate">Date</label><input class="form-control" id="expenseDate" name="expense_date" type="date" value="<?= date('Y-m-d') ?>" required></div><div class="col-md-4"><label class="form-label" for="expenseAmount">Amount</label><input class="form-control" id="expenseAmount" name="amount" type="number" min="0.01" step="0.01" required></div><div class="col-md-4"><label class="form-label" for="expenseMethod">Payment method</label><select class="form-select" id="expenseMethod" name="payment_method"><option value="CASH">Cash</option><option value="BANK">Bank</option><option value="MOBILE_MONEY">Mobile money</option><option value="CREDIT">Credit</option><option value="OTHER">Other</option></select></div><div class="col-12"><label class="form-label" for="expenseDescription">Description</label><input class="form-control" id="expenseDescription" name="description" required maxlength="500"></div><div class="col-md-6"><label class="form-label" for="expenseAttachment">Attachment</label><input class="form-control" id="expenseAttachment" name="attachment" type="file" accept="application/pdf,image/jpeg,image/png,image/webp"></div><div class="col-md-6"><label class="form-label" for="expenseNotes">Notes</label><textarea class="form-control" id="expenseNotes" name="notes" rows="2"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Record expense</button></div></form></div></div></div>
<div class="modal fade" id="categoryModal" tabindex="-1" aria-labelledby="categoryTitle" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><form data-api-form data-endpoint="expenses/categories" data-method="POST" data-success-redirect="<?= Helpers::escape(Helpers::appPath($config,'/expenses')) ?>"><div class="modal-header"><h2 class="modal-title fs-5" id="categoryTitle">New expense category</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><label class="form-label" for="expenseCategoryName">Name</label><input class="form-control" id="expenseCategoryName" name="name" required maxlength="120"><label class="form-label mt-3" for="expenseLedger">Expense ledger account</label><select class="form-select" id="expenseLedger" name="chart_account_id" required><option value="">Select account</option><?php foreach($expenseAccounts as$a):?><option value="<?= (int)$a['id'] ?>"><?= Helpers::escape($a['code'].' · '.$a['name']) ?></option><?php endforeach;?></select></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Create category</button></div></form></div></div></div><?php endif;?>
<?php require __DIR__.'/../layouts/footer.php'; ?>
