<?php
declare(strict_types=1);
use Karoor\Core\Helpers;
$views=['chart-of-accounts'=>'Chart of Accounts','accounts'=>'Financial Accounts','journals'=>'Journal Entries','ledger'=>'General Ledger','trial-balance'=>'Trial Balance','income-statement'=>'Income Statement','balance-sheet'=>'Balance Sheet','cash-flow'=>'Cash Flow','receivables'=>'Receivables','payables'=>'Payables','payments'=>'Payments'];
$financeView=is_string($_GET['view']??null)&&isset($views[$_GET['view']])?$_GET['view']:'trial-balance';
$pageTitle=$views[$financeView];$pageDescription='Double-entry accounting, balances, journals, and financial statements.';$breadcrumbs=[['label'=>'Finance','url'=>'/finance'],$pageTitle];$companyId=(int)$currentUser['company_id'];
$chartAccounts=$database->fetchAll('SELECT id,code,name,account_type,allow_manual_entries FROM chart_of_accounts WHERE company_id=:company AND is_active=1 AND deleted_at IS NULL ORDER BY code',['company'=>$companyId]);
$canCreate=$auth->can('finance.create')&&in_array($financeView,['chart-of-accounts','accounts','journals'],true);
$pageActions=static function()use($canCreate,$financeView):void{if($canCreate)echo '<button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#financeCreateModal"><i class="fa-solid fa-plus" aria-hidden="true"></i> New '.Helpers::escape($financeView==='journals'?'journal':'account').'</button>';};
$columns=[
'chart-of-accounts'=>[['code','Code','text'],['name','Account','text'],['account_type','Type','status'],['account_subtype','Subtype','text'],['parent_name','Parent','text'],['balance','Balance','currency'],['is_active','Active','boolean']],
'accounts'=>[['name','Account','text'],['account_kind','Kind','status'],['chart_name','Ledger account','text'],['account_number','Number','text'],['currency_code','Currency','text'],['balance','Balance','currency']],
'journals'=>[['entry_number','Entry','text'],['entry_date','Date','date'],['description','Description','text'],['total_debit','Debit','currency'],['total_credit','Credit','currency'],['status','Status','status'],['id','Actions','actions']],
'cash-flow'=>[['payment_method','Method','status'],['cash_in','Cash in','currency'],['cash_out','Cash out','currency'],['net_cash','Net cash','currency']],
'receivables'=>[['code','Customer code','text'],['name','Customer','text'],['balance','Balance due','currency']],
'payables'=>[['code','Supplier code','text'],['name','Supplier','text'],['balance','Balance due','currency']],
'payments'=>[['payment_number','Payment','text'],['payment_date','Date','datetime'],['direction','Direction','status'],['payment_method','Method','status'],['account_name','Account','text'],['amount','Amount','currency']],
];
$columns['ledger']=$columns['trial-balance']=$columns['income-statement']=$columns['balance-sheet']=[['code','Code','text'],['name','Account','text'],['account_type','Type','status'],['debit','Debit','currency'],['credit','Credit','currency'],['balance','Balance','currency']];
require __DIR__.'/../layouts/header.php';
?>
<nav class="nav nav-pills flex-nowrap overflow-auto mb-4" aria-label="Finance sections"><?php foreach($views as$key=>$label):?><a class="nav-link<?= $key===$financeView?' active':'' ?>" href="<?= Helpers::escape(Helpers::appPath($config,'/finance?view='.$key)) ?>"><?= Helpers::escape($label) ?></a><?php endforeach;?></nav>
<section class="surface-card">
 <div class="card-header-row"><div><h2><?= Helpers::escape($pageTitle) ?></h2><p>Live values from posted journals and operational transactions.</p></div></div>
 <?php if(in_array($financeView,['journals','ledger','trial-balance','income-statement','balance-sheet','cash-flow'],true)):?><form class="card-body-pad border-bottom row g-2 align-items-end" data-table-filters="financeTable"><div class="col-md-4"><label class="form-label" for="financeStart">From</label><input class="form-control" id="financeStart" name="start_date" type="date" value="<?= date('Y-01-01') ?>"></div><div class="col-md-4"><label class="form-label" for="financeEnd">To</label><input class="form-control" id="financeEnd" name="end_date" type="date" value="<?= date('Y-m-d') ?>"></div><div class="col-md-4 d-flex gap-2"><button class="btn btn-outline-primary" type="submit">Apply</button><button class="btn btn-outline-secondary" type="reset">Reset</button></div></form><?php endif;?>
 <div class="table-responsive"><table class="table align-middle mb-0" id="financeTable" data-api-table data-endpoint="finance/<?= Helpers::escape($financeView) ?>"><thead><tr><?php foreach($columns[$financeView]as[$field,$label,$format]):?><th data-field="<?= Helpers::escape($field) ?>"<?= $format!=='text'?' data-format="'.Helpers::escape($format).'"':'' ?>><?= Helpers::escape($label) ?></th><?php endforeach;?></tr></thead><tbody></tbody></table></div>
 <?php if(in_array($financeView,['journals','payments'],true)):?><div class="card-body-pad d-flex justify-content-end gap-2"><span class="text-secondary align-self-center">Page <span data-table-current="financeTable">1</span></span><button class="btn btn-outline-secondary" type="button" data-table-page="financeTable" data-page="previous">Previous</button><button class="btn btn-outline-secondary" type="button" data-table-page="financeTable" data-page="next">Next</button></div><?php endif;?>
</section>
<?php if($canCreate):?><div class="modal fade" id="financeCreateModal" tabindex="-1" aria-labelledby="financeCreateTitle" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content">
<?php if($financeView==='chart-of-accounts'):?><form data-api-form data-endpoint="finance/chart-of-accounts" data-method="POST" data-success-redirect="<?= Helpers::escape(Helpers::appPath($config,'/finance?view=chart-of-accounts')) ?>"><div class="modal-header"><h2 class="modal-title fs-5" id="financeCreateTitle">New chart account</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-4"><label class="form-label" for="coaCode">Code</label><input class="form-control" id="coaCode" name="code" required maxlength="30"></div><div class="col-md-8"><label class="form-label" for="coaName">Name</label><input class="form-control" id="coaName" name="name" required maxlength="150"></div><div class="col-md-4"><label class="form-label" for="coaType">Type</label><select class="form-select" id="coaType" name="account_type" required><option value="ASSET">Asset</option><option value="LIABILITY">Liability</option><option value="EQUITY">Equity</option><option value="REVENUE">Revenue</option><option value="EXPENSE">Expense</option></select></div><div class="col-md-4"><label class="form-label" for="coaNormal">Normal balance</label><select class="form-select" id="coaNormal" name="normal_balance"><option value="DEBIT">Debit</option><option value="CREDIT">Credit</option></select></div><div class="col-md-4"><label class="form-label" for="coaSubtype">Subtype</label><input class="form-control" id="coaSubtype" name="account_subtype" required maxlength="60"></div><div class="col-12"><label class="form-label" for="coaParent">Parent</label><select class="form-select" id="coaParent" name="parent_id"><option value="">None</option><?php foreach($chartAccounts as$account):?><option value="<?= (int)$account['id'] ?>"><?= Helpers::escape($account['code'].' · '.$account['name']) ?></option><?php endforeach;?></select></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Create account</button></div></form>
<?php elseif($financeView==='accounts'):?><form data-api-form data-endpoint="finance/accounts" data-method="POST" data-success-redirect="<?= Helpers::escape(Helpers::appPath($config,'/finance?view=accounts')) ?>"><div class="modal-header"><h2 class="modal-title fs-5" id="financeCreateTitle">New financial account</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label" for="accountName">Name</label><input class="form-control" id="accountName" name="name" required maxlength="150"></div><div class="col-md-6"><label class="form-label" for="accountChart">Asset ledger account</label><select class="form-select" id="accountChart" name="chart_account_id" required><option value="">Select account</option><?php foreach($chartAccounts as$account):?><?php if($account['account_type']==='ASSET'):?><option value="<?= (int)$account['id'] ?>"><?= Helpers::escape($account['code'].' · '.$account['name']) ?></option><?php endif;?><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label" for="accountKind">Kind</label><select class="form-select" id="accountKind" name="account_kind"><option value="CASH">Cash</option><option value="BANK">Bank</option><option value="MOBILE_MONEY">Mobile money</option><option value="OTHER">Other</option></select></div><div class="col-md-6"><label class="form-label" for="accountNumber">Account number</label><input class="form-control" id="accountNumber" name="account_number" maxlength="100"></div><div class="col-md-6"><label class="form-label" for="openingBalance">Opening balance</label><input class="form-control" id="openingBalance" name="opening_balance" type="number" step="0.01" value="0"></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Create account</button></div></form>
<?php else:?><form id="journalCreateForm"><div class="modal-header"><h2 class="modal-title fs-5" id="financeCreateTitle">New journal entry</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><div class="row g-3 mb-3"><div class="col-md-4"><label class="form-label" for="journalDate">Entry date</label><input class="form-control" id="journalDate" name="entry_date" type="date" value="<?= date('Y-m-d') ?>" required></div><div class="col-md-8"><label class="form-label" for="journalDescription">Description</label><input class="form-control" id="journalDescription" name="description" required maxlength="500"></div></div><div class="table-responsive"><table class="table"><thead><tr><th>Account</th><th>Line description</th><th>Debit</th><th>Credit</th><th><span class="visually-hidden">Remove</span></th></tr></thead><tbody id="journalLines"></tbody></table></div><button class="btn btn-sm btn-outline-primary" id="addJournalLine" type="button"><i class="fa-solid fa-plus" aria-hidden="true"></i> Add line</button><div class="form-check mt-3"><input class="form-check-input" id="postJournal" name="post_now" type="checkbox"><label class="form-check-label" for="postJournal">Post immediately</label></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Save journal</button></div></form><script type="application/json" id="journalAccountData"><?= json_encode(array_values(array_filter($chartAccounts,static fn($a)=>(bool)$a['allow_manual_entries'])),JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script><?php endif;?>
</div></div></div><?php endif;?>
<?php require __DIR__.'/../layouts/footer.php'; ?>
