<?php
declare(strict_types=1);
use Karoor\Core\Helpers;

$tabDefinitions = [
    'company' => ['label' => 'Company', 'permission' => 'settings.manage'],
    'application' => ['label' => 'Application', 'permission' => 'settings.manage'],
    'numbering' => ['label' => 'Numbering', 'permission' => 'settings.manage'],
    'users' => ['label' => 'Users', 'permission' => 'users.manage'],
    'roles' => ['label' => 'Roles & Permissions', 'permission' => 'roles.manage'],
    'audit' => ['label' => 'Audit Log', 'permission' => 'audit.view'],
    'backups' => ['label' => 'Backups', 'permission' => 'backups.manage'],
];
$tabs = array_filter($tabDefinitions, static fn(array $tab): bool => $auth->can($tab['permission']));
$requestedView = is_string($_GET['view'] ?? null) ? $_GET['view'] : '';
$settingsView = isset($tabs[$requestedView]) ? $requestedView : (array_key_first($tabs) ?? 'company');
$pageTitle = $tabs[$settingsView]['label'] ?? 'System';
$pageDescription = 'Secure company administration, access control, audit history, and application preferences.';
$breadcrumbs = [['label' => 'System'], $pageTitle];
$companyId = (int)$currentUser['company_id'];
$company = $settings = $sequences = $roles = $permissionsByModule = $branches = $warehouses = [];

if (in_array($settingsView, ['company', 'application', 'numbering'], true)) {
    $company = $database->fetchOne('SELECT * FROM companies WHERE id=:id', ['id' => $companyId]) ?? [];
    foreach ($database->fetchAll('SELECT setting_key,setting_value FROM settings WHERE company_id=:company', ['company' => $companyId]) as $row) {
        $settings[(string)$row['setting_key']] = $row['setting_value'];
    }
    $sequences = $database->fetchAll('SELECT id,document_type,prefix,next_number,padding,reset_period FROM document_sequences WHERE company_id=:company ORDER BY document_type', ['company' => $companyId]);
}
if ($settingsView === 'users') {
    $roles = $database->fetchAll('SELECT id,name FROM roles WHERE (company_id=:company OR company_id IS NULL) AND is_active=1 AND deleted_at IS NULL ORDER BY name', ['company' => $companyId]);
    $branches = $database->fetchAll('SELECT id,name FROM branches WHERE company_id=:company AND is_active=1 AND deleted_at IS NULL ORDER BY name', ['company' => $companyId]);
    $warehouses = $database->fetchAll('SELECT id,name FROM warehouses WHERE company_id=:company AND is_active=1 AND deleted_at IS NULL ORDER BY name', ['company' => $companyId]);
}
if ($settingsView === 'roles') {
    foreach ($database->fetchAll('SELECT id,module,name,description FROM permissions ORDER BY module,name') as $permission) {
        $permissionsByModule[(string)$permission['module']][] = $permission;
    }
}
$pageActions = static function () use ($settingsView): void {
    if ($settingsView === 'users') echo '<button class="btn btn-primary" type="button" data-new-user><i class="fa-solid fa-user-plus" aria-hidden="true"></i> New user</button>';
    if ($settingsView === 'roles') echo '<button class="btn btn-primary" type="button" data-new-role><i class="fa-solid fa-shield-halved" aria-hidden="true"></i> New role</button>';
};
require __DIR__ . '/../layouts/header.php';
?>
<nav class="nav nav-pills flex-nowrap overflow-auto mb-4" aria-label="System administration sections">
<?php foreach ($tabs as $key => $tab): ?><a class="nav-link<?= $key === $settingsView ? ' active' : '' ?>" href="<?= Helpers::escape(Helpers::appPath($config, '/settings?view='.$key)) ?>"><?= Helpers::escape($tab['label']) ?></a><?php endforeach; ?>
</nav>

<?php if ($settingsView === 'users'): ?>
<section class="surface-card">
    <div class="card-header-row"><div><h2>User accounts</h2><p>Assign branch access and one or more permission-bearing roles.</p></div><div class="input-group" style="max-width:320px"><span class="input-group-text"><i class="fa-solid fa-search" aria-hidden="true"></i></span><label class="visually-hidden" for="userSearch">Search users</label><input class="form-control" id="userSearch" type="search" data-table-search="usersTable" placeholder="Name, username, or email…"></div></div>
    <div class="table-responsive"><table class="table align-middle mb-0" id="usersTable" data-api-table data-endpoint="system/users" data-current-user-id="<?= (int)$currentUser['id'] ?>"><thead><tr><th data-field="full_name">Name</th><th data-field="username">Username</th><th data-field="email">Email</th><th data-field="roles">Roles</th><th data-field="status" data-format="status">Status</th><th data-field="last_login_at" data-format="datetime">Last login</th><th data-field="id" data-format="actions">Actions</th></tr></thead><tbody></tbody></table></div>
    <div class="card-body-pad d-flex justify-content-end gap-2"><span class="text-secondary align-self-center">Page <span data-table-current="usersTable">1</span></span><button class="btn btn-outline-secondary" type="button" data-table-page="usersTable" data-page="previous">Previous</button><button class="btn btn-outline-secondary" type="button" data-table-page="usersTable" data-page="next">Next</button></div>
</section>
<div class="modal fade" id="userModal" tabindex="-1" aria-labelledby="userModalTitle" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><form id="systemUserForm">
    <div class="modal-header"><h2 class="modal-title fs-5" id="userModalTitle">New user</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div>
    <div class="modal-body"><input type="hidden" name="user_id"><div class="row g-3">
        <div class="col-md-6"><label class="form-label" for="userFullName">Full name</label><input class="form-control" id="userFullName" name="full_name" required maxlength="190" autocomplete="name"></div>
        <div class="col-md-6"><label class="form-label" for="userName">Username</label><input class="form-control" id="userName" name="username" required minlength="3" maxlength="80" autocomplete="username"></div>
        <div class="col-md-6"><label class="form-label" for="userEmail">Email</label><input class="form-control" id="userEmail" name="email" type="email" required maxlength="190" autocomplete="email"></div>
        <div class="col-md-6"><label class="form-label" for="userPhone">Phone</label><input class="form-control" id="userPhone" name="phone" maxlength="50" autocomplete="tel"></div>
        <div class="col-md-6"><label class="form-label" for="userPassword">Password</label><input class="form-control" id="userPassword" name="password" type="password" minlength="12" maxlength="4096" autocomplete="new-password"><div class="form-text">At least 12 characters. Leave blank when editing to keep the current password.</div></div>
        <div class="col-md-3"><label class="form-label" for="userStatus">Status</label><select class="form-select" id="userStatus" name="status"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="LOCKED">Locked</option></select></div>
        <div class="col-md-3"><label class="form-label" for="userLocale">Locale</label><input class="form-control" id="userLocale" name="locale" value="en" maxlength="10"></div>
        <div class="col-md-6"><label class="form-label" for="userBranch">Branch</label><select class="form-select" id="userBranch" name="branch_id"><option value="">All branches</option><?php foreach ($branches as $branch): ?><option value="<?= (int)$branch['id'] ?>"><?= Helpers::escape((string)$branch['name']) ?></option><?php endforeach; ?></select></div>
        <div class="col-md-6"><label class="form-label" for="userWarehouse">Default warehouse</label><select class="form-select" id="userWarehouse" name="default_warehouse_id"><option value="">Company default</option><?php foreach ($warehouses as $warehouse): ?><option value="<?= (int)$warehouse['id'] ?>"><?= Helpers::escape((string)$warehouse['name']) ?></option><?php endforeach; ?></select></div>
        <fieldset class="col-12"><legend class="form-label">Roles</legend><div class="row g-2" data-role-options><?php foreach ($roles as $role): ?><div class="col-sm-6 col-lg-4"><label class="form-check surface-option"><input class="form-check-input" type="checkbox" name="role_ids" value="<?= (int)$role['id'] ?>"><span class="form-check-label"><?= Helpers::escape((string)$role['name']) ?></span></label></div><?php endforeach; ?></div><div class="invalid-feedback d-none" data-role-error>Select at least one role.</div></fieldset>
        <div class="col-12"><label class="form-check"><input class="form-check-input" type="checkbox" name="force_password_change" value="1" checked><span class="form-check-label">Require a password change on the next sign-in</span></label></div>
    </div></div>
    <div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Create user</button></div>
</form></div></div></div>

<?php elseif ($settingsView === 'roles'): ?>
<section class="surface-card"><div class="card-header-row"><div><h2>Roles & permissions</h2><p>System roles are protected; create company roles for tailored access.</p></div></div><div class="table-responsive"><table class="table align-middle mb-0" id="rolesTable" data-api-table data-endpoint="system/roles"><thead><tr><th data-field="name">Role</th><th data-field="description">Description</th><th data-field="user_count" data-format="number">Users</th><th data-field="permission_count" data-format="number">Permissions</th><th data-field="is_active" data-format="boolean">Active</th><th data-field="id" data-format="actions">Actions</th></tr></thead><tbody></tbody></table></div></section>
<div class="modal fade" id="roleModal" tabindex="-1" aria-labelledby="roleModalTitle" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><form id="systemRoleForm">
    <div class="modal-header"><h2 class="modal-title fs-5" id="roleModalTitle">New role</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div>
    <div class="modal-body"><input type="hidden" name="role_id"><div class="row g-3 mb-4"><div class="col-md-5"><label class="form-label" for="roleName">Role name</label><input class="form-control" id="roleName" name="name" required maxlength="100"></div><div class="col-md-5"><label class="form-label" for="roleDescription">Description</label><input class="form-control" id="roleDescription" name="description" maxlength="255"></div><div class="col-md-2 d-flex align-items-end"><label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked><span class="form-check-label">Active</span></label></div></div>
        <div class="d-flex flex-wrap align-items-center justify-content-between gap-2 mb-3"><div><h3 class="fs-6 mb-1">Permissions</h3><p class="text-secondary small mb-0">Every API request verifies these permissions on the server.</p></div><button class="btn btn-sm btn-outline-secondary" type="button" data-toggle-permissions>Select all</button></div>
        <div class="permission-grid"><?php foreach ($permissionsByModule as $module => $modulePermissions): ?><fieldset class="permission-group"><legend><?= Helpers::escape(ucwords(str_replace(['_', '-'], ' ', $module))) ?></legend><?php foreach ($modulePermissions as $permission): ?><label class="form-check"><input class="form-check-input" type="checkbox" name="permission_ids" value="<?= (int)$permission['id'] ?>"><span class="form-check-label"><strong><?= Helpers::escape((string)$permission['name']) ?></strong><?php if ($permission['description'] !== null): ?><small><?= Helpers::escape((string)$permission['description']) ?></small><?php endif; ?></span></label><?php endforeach; ?></fieldset><?php endforeach; ?></div>
    </div>
    <div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Create role</button></div>
</form></div></div></div>

<?php elseif ($settingsView === 'audit'): ?>
<section class="surface-card">
    <div class="card-header-row"><div><h2>Audit log</h2><p>Immutable security and business activity recorded by the backend.</p></div></div>
    <form class="card-body-pad border-bottom row g-2 align-items-end" data-table-filters="auditTable"><div class="col-md-3"><label class="form-label" for="auditModule">Module</label><input class="form-control" id="auditModule" name="module" maxlength="60" placeholder="e.g. sales"></div><div class="col-md-3"><label class="form-label" for="auditAction">Action</label><input class="form-control" id="auditAction" name="action" maxlength="60" placeholder="e.g. CREATE"></div><div class="col-md-3"><label class="form-label" for="auditUser">User ID</label><input class="form-control" id="auditUser" name="user_id" type="number" min="1"></div><div class="col-md-3 d-flex gap-2"><button class="btn btn-outline-primary" type="submit">Apply</button><button class="btn btn-outline-secondary" type="reset">Reset</button></div></form>
    <div class="table-responsive"><table class="table align-middle mb-0" id="auditTable" data-api-table data-endpoint="system/audit"><thead><tr><th data-field="created_at" data-format="datetime">Date</th><th data-field="user_name">User</th><th data-field="action" data-format="status">Action</th><th data-field="module">Module</th><th data-field="record_type">Record type</th><th data-field="record_id">Record ID</th><th data-field="ip_address">IP address</th></tr></thead><tbody></tbody></table></div>
    <div class="card-body-pad d-flex justify-content-end gap-2"><span class="text-secondary align-self-center">Page <span data-table-current="auditTable">1</span></span><button class="btn btn-outline-secondary" type="button" data-table-page="auditTable" data-page="previous">Previous</button><button class="btn btn-outline-secondary" type="button" data-table-page="auditTable" data-page="next">Next</button></div>
</section>

<?php elseif ($settingsView === 'backups'): ?>
<section class="surface-card"><div class="card-header-row"><div><h2>Database backups</h2><p>Create, download, and remove protected SQL archives.</p></div><button class="btn btn-primary" type="button" data-backup-create><i class="fa-solid fa-database" aria-hidden="true"></i> Create backup</button></div><div class="table-responsive"><table class="table align-middle mb-0" id="backupTable" data-api-table data-endpoint="system/backups" data-download-base="<?= Helpers::escape(Helpers::appPath($config, '/api/v1/system/backups')) ?>"><thead><tr><th data-field="filename">Backup</th><th data-field="file_size" data-format="number">Bytes</th><th data-field="status" data-format="status">Status</th><th data-field="created_at" data-format="datetime">Created</th><th data-field="id" data-format="actions">Actions</th></tr></thead><tbody></tbody></table></div></section>

<?php elseif ($settingsView === 'numbering'): ?>
<section class="surface-card"><div class="card-header-row"><div><h2>Document numbering</h2><p>Prefixes and counters remain unique per company and branch.</p></div></div><form id="numberingSettingsForm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Document</th><th>Prefix</th><th>Next number</th><th>Padding</th><th>Reset</th></tr></thead><tbody><?php foreach ($sequences as $i => $sequence): ?><tr data-sequence-row data-id="<?= (int)$sequence['id'] ?>"><td><?= Helpers::escape((string)$sequence['document_type']) ?></td><td><label class="visually-hidden" for="prefix<?= $i ?>">Prefix</label><input class="form-control" id="prefix<?= $i ?>" name="prefix" value="<?= Helpers::escape((string)$sequence['prefix']) ?>" pattern="[A-Za-z0-9/_-]{1,20}" required></td><td><?= (int)$sequence['next_number'] ?></td><td><label class="visually-hidden" for="padding<?= $i ?>">Padding</label><input class="form-control" id="padding<?= $i ?>" name="padding" type="number" min="1" max="12" value="<?= (int)$sequence['padding'] ?>" required></td><td><label class="visually-hidden" for="reset<?= $i ?>">Reset period</label><select class="form-select" id="reset<?= $i ?>" name="reset_period"><?php foreach (['NEVER','YEARLY','MONTHLY'] as $period): ?><option<?= $period === $sequence['reset_period'] ? ' selected' : '' ?>><?= $period ?></option><?php endforeach; ?></select></td></tr><?php endforeach; ?></tbody></table></div><div class="card-body-pad d-flex justify-content-end"><button class="btn btn-primary" type="submit">Save numbering</button></div></form></section>

<?php elseif ($settingsView === 'application'): ?>
<section class="surface-card"><div class="card-header-row"><div><h2>Application preferences</h2><p>Defaults used across invoices, receipts, POS, payroll, and sessions.</p></div></div><form class="card-body-pad" id="applicationSettingsForm"><div class="row g-3"><div class="col-md-4"><label class="form-label" for="currencyCode">Currency code</label><input class="form-control" id="currencyCode" name="currency.code" value="<?= Helpers::escape((string)($settings['currency.code'] ?? $company['currency_code'] ?? 'ETB')) ?>" pattern="[A-Za-z]{3}" required></div><div class="col-md-4"><label class="form-label" for="currencySymbol">Currency symbol</label><input class="form-control" id="currencySymbol" name="currency.symbol" value="<?= Helpers::escape((string)($settings['currency.symbol'] ?? 'ETB')) ?>" maxlength="10"></div><div class="col-md-4"><label class="form-label" for="appTimezone">Timezone</label><input class="form-control" id="appTimezone" name="timezone" value="<?= Helpers::escape((string)($settings['timezone'] ?? 'Africa/Addis_Ababa')) ?>" required></div><div class="col-md-4"><label class="form-label" for="dateFormat">Date format</label><input class="form-control" id="dateFormat" name="date.format" value="<?= Helpers::escape((string)($settings['date.format'] ?? 'Y-m-d')) ?>" required></div><div class="col-md-4"><label class="form-label" for="paperWidth">Receipt width</label><select class="form-select" id="paperWidth" name="receipt.paper_width"><option value="58"<?= ($settings['receipt.paper_width'] ?? '80') === '58' ? ' selected' : '' ?>>58mm</option><option value="80"<?= ($settings['receipt.paper_width'] ?? '80') === '80' ? ' selected' : '' ?>>80mm</option></select></div><div class="col-md-4"><label class="form-label" for="recordsPerPage">Records per page</label><input class="form-control" id="recordsPerPage" name="system.records_per_page" type="number" min="10" max="100" value="<?= Helpers::escape((string)($settings['system.records_per_page'] ?? '25')) ?>"></div><div class="col-12"><label class="form-label" for="invoiceFooter">Invoice footer</label><textarea class="form-control" id="invoiceFooter" name="invoice.footer" rows="3"><?= Helpers::escape((string)($settings['invoice.footer'] ?? '')) ?></textarea></div></div><div class="mt-4 d-flex justify-content-end"><button class="btn btn-primary" type="submit">Save preferences</button></div></form></section>

<?php else: ?>
<section class="surface-card"><div class="card-header-row"><div><h2>Company profile</h2><p>Identity and tax details shown on invoices, receipts, and reports.</p></div></div><form class="card-body-pad" id="companySettingsForm"><div class="row g-3"><div class="col-md-6"><label class="form-label" for="companyName">Company name</label><input class="form-control" id="companyName" name="name" value="<?= Helpers::escape((string)($company['name'] ?? '')) ?>" required></div><div class="col-md-6"><label class="form-label" for="legalName">Legal name</label><input class="form-control" id="legalName" name="legal_name" value="<?= Helpers::escape((string)($company['legal_name'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label" for="taxNumber">Tax number</label><input class="form-control" id="taxNumber" name="tax_number" value="<?= Helpers::escape((string)($company['tax_number'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label" for="vatNumber">VAT number</label><input class="form-control" id="vatNumber" name="vat_number" value="<?= Helpers::escape((string)($company['vat_number'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label" for="registrationNumber">Registration number</label><input class="form-control" id="registrationNumber" name="registration_number" value="<?= Helpers::escape((string)($company['registration_number'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label" for="companyPhone">Phone</label><input class="form-control" id="companyPhone" name="phone" value="<?= Helpers::escape((string)($company['phone'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label" for="companyEmail">Email</label><input class="form-control" id="companyEmail" name="email" type="email" value="<?= Helpers::escape((string)($company['email'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label" for="companyWebsite">Website</label><input class="form-control" id="companyWebsite" name="website" type="url" value="<?= Helpers::escape((string)($company['website'] ?? '')) ?>"></div><div class="col-md-6"><label class="form-label" for="addressLine">Address</label><input class="form-control" id="addressLine" name="address_line1" value="<?= Helpers::escape((string)($company['address_line1'] ?? '')) ?>"></div><div class="col-md-3"><label class="form-label" for="companyCity">City</label><input class="form-control" id="companyCity" name="city" value="<?= Helpers::escape((string)($company['city'] ?? '')) ?>"></div><div class="col-md-3"><label class="form-label" for="companyRegion">Region</label><input class="form-control" id="companyRegion" name="region" value="<?= Helpers::escape((string)($company['region'] ?? '')) ?>"></div></div><div class="mt-4 d-flex justify-content-end"><button class="btn btn-primary" type="submit">Save company</button></div></form></section>
<?php endif; ?>
<?php require __DIR__ . '/../layouts/footer.php'; ?>
